### PR TITLE
Dockerize jore3 importer

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19)

Closes: https://github.com/HSLdevcom/jore4/issues/374
Depends on https://github.com/HSLdevcom/jore4-jore3-importer/pull/25

### CODE REVIEW

**Review by pkainulainen-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19)* status: 0 of 53 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[pom.xml, line 194 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-Mj2voLME-jDL0pdS2MQ:-Mj2voLME-jDL0pdS2MR:bnci400) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e2d9fa51b65688c1be823210dff8da550fc51df6/pom.xml#L194)):*
> ```XML
>             <build>
>                 <filters>
>                     <filter>profiles/${build.profile.id}/config.${user.name}.properties</filter>
> ```

The value of the `filter` property should be replaced with: `${build.property.file}`. This way the used property file is specified only once when the value of the `build.property.file` property is set.
___
*[pom.xml, line 426 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-Mj37vZ91sFWB51Z7F18:-Mj37vZ91sFWB51Z7F19:b-rj6chh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e2d9fa51b65688c1be823210dff8da550fc51df6/pom.xml#L426)):*
> ```XML
>                         <target>
>                             <packageName>fi.hsl.jore.importer.jooq</packageName>
>                             <directory>${project.build.sourceDirectory}/generated-sources/jooq</directory>
> ```

I am not a big fan of putting generated classes to version control because it adds unnecessary noise to pull requests. However, I can live with it if Jarkko or Jörg thinks that this is a good idea.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19)* status: 0 of 53 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[pom.xml, line 194 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-Mj2voLME-jDL0pdS2MQ:-Mj491Vo9G_PX-zsB-38:b-a98sh1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e2d9fa51b65688c1be823210dff8da550fc51df6/pom.xml#L194)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The value of the `filter` property should be replaced with: `${build.property.file}`. This way the used property file is specified only once when the value of the `build.property.file` property is set.
</blockquote></details>

Done as a fix to a previous commit

**Comment by pallost** [comment]
Depends on https://github.com/HSLdevcom/jore4-jore3-importer/pull/25

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19)* status: 0 of 53 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @pkainulainen-vincit)

___
*[pom.xml, line 426 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-Mj37vZ91sFWB51Z7F18:-MjEDian1PxhmIhdt0g4:b1lipho) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e2d9fa51b65688c1be823210dff8da550fc51df6/pom.xml#L426)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I am not a big fan of putting generated classes to version control because it adds unnecessary noise to pull requests. However, I can live with it if Jarkko or Jörg thinks that this is a good idea.
</blockquote></details>

I'm not a big fan of this too, I'd rather stick with the single source of truth. But when we had a discussion about this, there were some good-ish points for putting these in the version control.

But I'd rather someone else would remember what the reasons were, I think they might have been related to it being difficult to create a db instance for this during the build process :thinking:

**Review by pkainulainen-vincit — APPROVED** [review]
Looks good to me

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-:-MjEVJjE2S9VUwVH1ACr:b-owaf1x)* status: 0 of 53 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @pkainulainen-vincit)

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19)* status: 2 of 64 files reviewed, 3 unresolved discussions (waiting on @pallost and @pkainulainen-vincit)

___
*[Dockerfile, line 28 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-MjEZBN_E2WEKaNTmuJ-:-MjEZBNa4-4C7YzHvGF2:b7sgckj) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/1cc6152425a6294ba8219e208128ee986177338f/Dockerfile#L28)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> # copy over compiled jar
> COPY --from=builder /build/target/*.jar /usr/src/jore4-auth/auth-backend.jar
> # read docker secrets into environment varaibles and run application
> CMD /bin/bash -c "source /tmp/read-secrets.sh && java -jar /usr/src/jore4-auth/auth-backend.jar"
> ```
</details>


The name of directory and jar file may be need to be changed.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19)* status: 1 of 64 files reviewed, 3 unresolved discussions (waiting on @jarkkoka and @pkainulainen-vincit)

___
*[Dockerfile, line 28 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-MjEZBN_E2WEKaNTmuJ-:-MjE_yDF5rH-SiOEwfgT:b-6sdql8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/1cc6152425a6294ba8219e208128ee986177338f/Dockerfile#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> # copy over compiled jar
> COPY --from=builder /build/target/*.jar /usr/src/jore4-auth/auth-backend.jar
> # read docker secrets into environment varaibles and run application
> CMD /bin/bash -c "source /tmp/read-secrets.sh && java -jar /usr/src/jore4-auth/auth-backend.jar"
> ```

The name of directory and jar file may be need to be changed.
</blockquote></details>

good catch! fixes it
___
*[pom.xml, line 426 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/19#-Mj37vZ91sFWB51Z7F18:-MjEa2gh3vL4wbkDx61M:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e2d9fa51b65688c1be823210dff8da550fc51df6/pom.xml#L426)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I'm not a big fan of this too, I'd rather stick with the single source of truth. But when we had a discussion about this, there were some good-ish points for putting these in the version control.

But I'd rather someone else would remember what the reasons were, I think they might have been related to it being difficult to create a db instance for this during the build process :thinking: 
</blockquote></details>

Done.

**Pull request merged**
