### PR TITLE
Import routes

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
Tests pass and the imported data is inserted into the network.network_routes table.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29)* status: all files reviewed, 6 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteMapper.java, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd3dTtBow2zWmIoBbC:-Mjd3dTtBow2zWmIoBbD:b-24m6ho) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteMapper.java#L27)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                 RouteId.from(getStringOrThrow(rs, "reitunnus")),
>                 LineId.from(getStringOrThrow(rs, "lintunnus")),
>                 getOptionalString(rs, "reinimi"),
>                 getOptionalString(rs, "reinimir")
> ```
</details>


`reinimilyh` and  `reinimilyhr` are missing.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java, line 81 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd6gj52GUWFFHleuHn:-Mjd6gj52GUWFFHleuHo:b2euf72) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java#L81)):*
> ```
>                  .set(TARGET_TABLE.NETWORK_ROUTE_NAME,
>                       STAGING_TABLE.NETWORK_ROUTE_NAME)
> ```

What makes this part a little bit hard to understand is that only one field is updated. I expect the reason being that other fields are part of composite ID value. I am not sure whether my assumption is correct or not. However, this crucial detail is not mentioned here even though it is not imminently obvious to the reader not very familiar with this code base. I think this point should be made clear to the reader in form of a comment.

Can you verify should route number be included here (e.g. with a test)? Noticed that there is no `RouteImportRepositoryTest`class like there is for other repositories used in tests. Maybe one should be added?
___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd8XKR6KJj-c5AQL4m:-Mjd8XKR6KJj-c5AQL4n:b-pb7nu6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java#L21)):*
> ```
> JrRoute
> ```

Database fields `reinimir` and  `reinimilyhr` are missing from here. Is that intentional? At least, there should be a comment in this class that they are not included.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd8qjRBesqRzFlqhD-:-Mjd8qjRBesqRzFlqhD0:bzeecbb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java#L42)):*
> ```
> name = "reinimilyh
> ```

Incorrect. Fix => `reinimir`
___
*[src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java, line 78 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdASg08MSm06e4K0Bo:-MjdASg08MSm06e4K0Bp:b-ksyksw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java#L78)):*
> ```
>        r.setNetworkRouteName(jsonbConverter.asJson(route.name()));
> ```

Why is route number not updated here? IMO, a comment is dictated if this is not a bug.
___
*[src/main/resources/db/migration/V9__init_routes.sql, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdBONDBKY_G7OFitQT:-MjdBONDBKY_G7OFitQU:b-dtfrz8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/resources/db/migration/V9__init_routes.sql#L9)):*
> ```
>    network_route_name       JSONB                                                NOT NULL,
> ```

In source database there are fields `reinimilyh` and  `reinimilyhr`. They are not mapped to this table. Possibly, there is uncertainty whether those fields are really needed in JORE4.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteMapper.java, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd3dTtBow2zWmIoBbC:-Mjh5qPW02h17KuGyqNn:b-113rul) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteMapper.java#L27)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                 RouteId.from(getStringOrThrow(rs, "reitunnus")),
>                 LineId.from(getStringOrThrow(rs, "lintunnus")),
>                 getOptionalString(rs, "reinimi"),
>                 getOptionalString(rs, "reinimir")
> ```

`reinimilyh` and  `reinimilyhr` are missing.
</blockquote></details>

I found one comment from Slack which suggests that the `reinimir` field might be deprecated. See: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

I assume that the Swedish translations aren't processed at the moment because Lasse didn't know how they will be stored.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java, line 81 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd6gj52GUWFFHleuHn:-Mjh2GES1WAzAjrMR2tn:b-57jru3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java#L81)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                  .set(TARGET_TABLE.NETWORK_ROUTE_NAME,
>                       STAGING_TABLE.NETWORK_ROUTE_NAME)
> ```

What makes this part a little bit hard to understand is that only one field is updated. I expect the reason being that other fields are part of composite ID value. I am not sure whether my assumption is correct or not. However, this crucial detail is not mentioned here even though it is not imminently obvious to the reader not very familiar with this code base. I think this point should be made clear to the reader in form of a comment.

Can you verify should route number be included here (e.g. with a test)? Noticed that there is no `RouteImportRepositoryTest`class like there is for other repositories used in tests. Maybe one should be added?
</blockquote></details>

My first impression was that only the name is updated because changing the other column values (except the timestamp) would either change the line of the route (i assume that this isn't allowed) or "creates a new route". For example, I assume that changing the route number "changes the identity of the route". However, I haven't been able to find out anything from the Slack yet.

Also, adding a test is for the `RouteImportRepository` is a good idea and I will do it.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd8XKR6KJj-c5AQL4m:-Mjh5T0nDbIjDHVyXqXz:btr5293) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> JrRoute
> ```

Database fields `reinimir` and  `reinimilyhr` are missing from here. Is that intentional? At least, there should be a comment in this class that they are not included.
</blockquote></details>

I found one comment from Slack which suggests that the `reinimir` field might be deprecated. See: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

I assume that the Swedish translations aren't processed at the moment because Lasse didn't know how they will be stored.
___
*[src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java, line 78 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdASg08MSm06e4K0Bo:-Mjh6isj2eT-LrSenIJH:bmd949m) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java#L78)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>        r.setNetworkRouteName(jsonbConverter.asJson(route.name()));
> ```

Why is route number not updated here? IMO, a comment is dictated if this is not a bug.
</blockquote></details>

My hunch is that route number isn't updated simply because it changes the identity of the route. For example, route 2 is a different route than route 3.
___
*[src/main/resources/db/migration/V9__init_routes.sql, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdBONDBKY_G7OFitQT:-Mjh6zX652HgeVb8XlT2:b-113rul) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/resources/db/migration/V9__init_routes.sql#L9)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>    network_route_name       JSONB                                                NOT NULL,
> ```

In source database there are fields `reinimilyh` and  `reinimilyhr`. They are not mapped to this table. Possibly, there is uncertainty whether those fields are really needed in JORE4.
</blockquote></details>

I found one comment from Slack which suggests that the `reinimir` field might be deprecated. See: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

I assume that the Swedish translations aren't processed at the moment because Lasse didn't know how they will be stored.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java, line 42 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd8qjRBesqRzFlqhD-:-Mjh73QMDcDFEhQYEE5s:b6zrrkh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java#L42)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> name = "reinimilyh
> ```

Incorrect. Fix => `reinimir`
</blockquote></details>

Good catch.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java, line 81 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd6gj52GUWFFHleuHn:-Mjh8HmT5MQguMsb1ii7:bi9wbqy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java#L81)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

My first impression was that only the name is updated because changing the other column values (except the timestamp) would either change the line of the route (i assume that this isn't allowed) or "creates a new route". For example, I assume that changing the route number "changes the identity of the route". However, I haven't been able to find out anything from the Slack yet.

Also, adding a test is for the `RouteImportRepository` is a good idea and I will do it.
</blockquote></details>

I took a look at the database (`network.network_routes` table) and this discussion: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH and it seems that the route number is parsed from the `network_route_ext_id` column. In other words, if the of the `network_route_ext_id` isn't updated, it doesn't make sense to update the route number either. Does this make any sense?
___
*[src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java, line 78 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdASg08MSm06e4K0Bo:-Mjh8yVe-uFCA1agLI_1:b-1q2blc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java#L78)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

My hunch is that route number isn't updated simply because it changes the identity of the route. For example, route 2 is a different route than route 3.
</blockquote></details>

I took a look at the database (`network.network_routes` table) and this discussion: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH and it seems that the route number is parsed from the `network_route_ext_id` column. In other words, if the of the `network_route_ext_id` isn't updated, it doesn't make sense to update the route number either. Does this make any sense?

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29)* status: all files reviewed, 3 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteMapper.java, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd3dTtBow2zWmIoBbC:-Mji9iGx-aNEdWk5uiFE:b-7hq4n1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/RouteMapper.java#L27)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I found one comment from Slack which suggests that the `reinimir` field might be deprecated. See: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

I assume that the Swedish translations aren't processed at the moment because Lasse didn't know how they will be stored.

</blockquote></details>

Ok. Thanks for sharing that discussion.

Actually, I took a look at Jore3 DB descriptions excelsheet and there those two fields were marked deprecated. That answers my question. I would still add a comment here (since those fields appear in source db table declaration) in order to be not confused again.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java, line 81 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd6gj52GUWFFHleuHn:-MjiAnymCRYLCOP_hQkJ:bo4uz14) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java#L81)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I took a look at the database (`network.network_routes` table) and this discussion: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH and it seems that the route number is parsed from the `network_route_ext_id` column. In other words, if the of the `network_route_ext_id` isn't updated, it doesn't make sense to update the route number either. Does this make any sense?
</blockquote></details>

Thanks for the clarification. I think by knowing this detail it makes now sense and that was kind of my initial assumption. Anyway, I would like to have a comment here stating this detail in order to not be confused again by this same matter.
___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mjd8XKR6KJj-c5AQL4m:-MjiDDTe7FmpttdBS6Nv:bzhlbcy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/jore3/entity/JrRoute.java#L21)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I found one comment from Slack which suggests that the `reinimir` field might be deprecated. See: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

I assume that the Swedish translations aren't processed at the moment because Lasse didn't know how they will be stored.
</blockquote></details>

As I mentioned in my other reply comment, those two fields are deprecated. That's the reason.
___
*[src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java, line 78 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdASg08MSm06e4K0Bo:-MjiChKL9Spmzlzm3g7Y:b5xl2yp) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/java/fi/hsl/jore/importer/feature/network/route/repository/RouteRepository.java#L78)):*
> https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

Ok. Makes sense. I would like to have this remark about route number being part of identity as a comment in this method.
___
*[src/main/resources/db/migration/V9__init_routes.sql, line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-MjdBONDBKY_G7OFitQT:-MjiEo35As2xXHSX3tqQ:b-r8xn3q) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fd9784e32f1db34def65eea7b12273fce88d53a1/src/main/resources/db/migration/V9__init_routes.sql#L9)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

I found one comment from Slack which suggests that the `reinimir` field might be deprecated. See: https://vincit.slack.com/archives/CNG9QULAH/p1619070409001100?thread_ts=1619000365.062100&cid=CNG9QULAH

I assume that the Swedish translations aren't processed at the moment because Lasse didn't know how they will be stored.

</blockquote></details>

I took a look at the Jore3 database field descriptions excelsheet and there the name abbreviation columns are marked deprecated (`reinimilyh` and `reinimilyhr`). That answers my question why they are not included in the target database table. However, since those fields exist in source database table definition, I would add a comment about the depreciation either here or into corresponding Java interface in order to be not confused again.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Looks good - especially the new nested test structure! Some minor typos requested to be fixed. Not anything critical that would mandate a re-review.

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-:-Mk6EHnh7jay_fLouN-O:b-ienm5t)* status: all files reviewed, 11 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[-- commits, line 13 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6BIVY0he2J_aa2vr-):*
> ```
> a
> ```

an
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java, line 84 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6BW3k0-ZhZHFcouiw:-Mk6BW3k0-ZhZHFcouix:b-z469fc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/main/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepository.java#L84)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                  // Only the name of the route is updated because changing
>                  // the other field values would either change the line of
>                  // the route or change the identity of the route.
>                  // Also, the value of the route_number column is parsed
>                  // from the value of the network_route_ext_id column. Thus,
>                  // both of them must be updated at the same time.
> ```
</details>


Thanks for clear explanation! :+1: 
___
*[src/test/java/fi/hsl/jore/importer/IntTest.java, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6BfH8BDDTYrOD0qde:-Mk6BfH8BDDTYrOD0qdf:b-ap5r4w) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/test/java/fi/hsl/jore/importer/IntTest.java#L7)):*
> ```
> *
> ```

I would prefer not to use star imports. 
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java, line 32 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6CngO7oMRIsOgf3PN:-Mk6CngO7oMRIsOgf3PO:bh5294u) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java#L32)):*
> ```
> IRouteImportRepository
> ```

I think you should add `final` qualifier to adhere to the style convention.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java, line 38 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6CaE57DNyPCHUuhAD:-Mk6CaE57DNyPCHUuhAE:b-gakaro) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java#L38)):*
> ```
> @Nested
> ```

:+1: 

Nesting tests makes them easier to read and more logical to understand. Clearly improves the quality of test code!
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java, line 154 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6EgOv9rQdnCc-7uhC:-Mk6EgOv9rQdnCc-7uhD:bll6tb3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java#L154)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                     final Map<RowStatus, Set<RoutePK>> result = importRepository.commitStagingToTarget();
> 
>                     RoutePK id = result.get(RowStatus.INSERTED).get().get();
>                     Set<RoutePK> dbIds = targetRepository.findAllIds();
> ```
</details>


Inconsistent use of `final` qualifier. I'd prefer to add it always when possible.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java, line 210 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6DppO9kWMVXQrQv2r:-Mk6DppO9kWMVXQrQv2s:bhs2kcy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java#L210)):*
> ```
> RoutePK
> ```

Would add `final` qualifier here (and below) to adhere to the style convention. 
___
*[src/test/resources/sql/destination/populate_routes.sql, line 7 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/29#-Mk6CBosBSACA-x1Zo01:-Mk6CBosBSACA-x1Zo02:bhwfsvh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e59ed045e77c5779e5930be3ce5b990c48328056/src/test/resources/sql/destination/populate_routes.sql#L7)):*
> ```
> Etelä-Hervants","sv_SE": "Central torget - Södra Hervants"
> ```

`Hervants` -> `Hervanta` (2 x)

**Pull request merged**
