### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
Resolves /HSLdevcom/jore4/issues/727

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
Well written!

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-:-N0FroS9CJXTLuKj-lj9:b-n6baix)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fijva2_dVG3RCZPUw:-N0Fijva2_dVG3RCZPUx:b-w0ta92) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L22)):*
> ```Markdown
> If you want to start the import job, you have to send a POST request to the path: `/job/import/start`. The API endpoint 
> will start the job and return its status. If an import job is already running, a new job isn't started and the return 
> value will reflect the status of the running job.
> ```

"currently running"



_Code quote:_
```Markdown
 running
```
___
*[README.md, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fkgw1BCszRNmqUw1h:-N0Fkgw1BCszRNmqUw1i:b-1wm5ob) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L34)):*
> ```Markdown
> 
> If you want to query the status of the latest import job, you have to send a GET request to the path: `/job/import/status`.
> The API endpoint returns the status of the latest import job. If no import job has been run, the API endpoint returns
> ```

I suggest either of the two following variants:

* "The API endpoint returns the status of an ongoing import job or the status of the latest finished import job in case there is no job currently running."
* "The API endpoint returns the status of an ongoing or the latest finished import job. Status of the latest finished job is returned in case there is no job currently running."



_Code quote:_
```Markdown
The API endpoint returns the status of the latest import job
```
___
*[README.md, line 84 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0FmJjW3eLFEWu9IOPA:-N0FmJjW3eLFEWu9IOPB:b93pq4y) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L84)):*
> ```Markdown
> 
> This application is basically a Spring Boot application which imports the data from the Jore 3 database to the Jore 4
> database by using Spring Batch. This application also provides a REST API which allows you to start the import job and 
> ```

I'd would augment the sentence a little bit.

"This application is basically a Spring Boot application which reads data from the Jore 3 database, makes some transformations to the data and finally writes it to the Jore 4 database by using Spring Batch library."



_Suggestion:_
```Markdown
This application is basically a Spring Boot application which imports the data from the Jore 3 database to the Jore 4
database by using Spring Batch.
```
___
*[README.md, line 147 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fnl6yA-Fl_9JIXNUu:-N0Fnl6zChhwZUbuqiie:b-57tggz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L147)):*
> ```Markdown
> * The `commitStep` moves the data from the staging table to the actual target table.
> 
> It's important to understand that the job which import data from the Jore 3 database to the importer's database don't follow
> ```

doesn't



_Code quote:_
```Markdown
don't
```
___
*[README.md, line 201 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0FofEv0J9hlp8DDvA4:-N0FofEv0J9hlp8DDvA5:bwy2vu6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L201)):*
> ```Markdown
> * The `exportRoutesStep` step imports route metadata from the importer's database to the Jore 4 database.
> * The `exportRouteGeometriesStep` step imports route geometries from the importer's database to the Jore 4 database.
> * The `exportJourneyPatternsStep` step creates new journey patterns to the Jore 4 database.
> ```

"imports journey pattern metadata (not including actual stop point sequences) from the importer's database to the Jore 4 database"



_Code quote:_
```Markdown
creates new journey patterns to the Jore 4 database
```
___
*[README.md, line 202 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fp8ebC-OCvtxPcSv9:-N0Fp8ebC-OCvtxPcSvA:buyvkqa) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L202)):*
> ```Markdown
> * The `exportRouteGeometriesStep` step imports route geometries from the importer's database to the Jore 4 database.
> * The `exportJourneyPatternsStep` step creates new journey patterns to the Jore 4 database.
> * The `exportJourneyPatternStopsStep` step imports links scheduled stop points with the created journey patterns.
> ```

"imports the sequence of scheduled stop point references for each journey pattern from the importer's database to the Jore 4 database"



_Code quote:_
```Markdown
imports links scheduled stop points with the created journey patterns
```

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 84 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0FmJjW3eLFEWu9IOPA:-N0Fs1x5DI3wdGZ6qmlr:b-og2qdj) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L84)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd would augment the sentence a little bit.

"This application is basically a Spring Boot application which reads data from the Jore 3 database, makes some transformations to the data and finally writes it to the Jore 4 database by using Spring Batch library."
</blockquote></details>

I meant to augment only the first sentence of the paragraph marked. The beginning part of the second sentence should not be removed even though in the diff it is marked as to be removed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`README.md` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fijva2_dVG3RCZPUw:-N0dHX0l5LRUR-ydiT49:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L22)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"currently running"
</blockquote></details>

Fixed.
___
*[`README.md` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fkgw1BCszRNmqUw1h:-N0dHkJF-Hp_XjUhkG11:b-elijx7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I suggest either of the two following variants:

* "The API endpoint returns the status of an ongoing import job or the status of the latest finished import job in case there is no job currently running."
* "The API endpoint returns the status of an ongoing or the latest finished import job. Status of the latest finished job is returned in case there is no job currently running."

</blockquote></details>

Good catch. I used the first variant.
___
*[`README.md` line 84 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0FmJjW3eLFEWu9IOPA:-N0dI3nfCjuBr5kjgc76:b-nxjtba) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L84)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I meant to augment only the first sentence of the paragraph marked. The beginning part of the second sentence should not be removed even though in the diff it is marked as to be removed.
</blockquote></details>

I replaced the original sentence with your version.
___
*[`README.md` line 147 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fnl6yA-Fl_9JIXNUu:-N0dIFzU-wOqomlWPjdO:b-qssebl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L147)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

doesn't
</blockquote></details>

fixed.
___
*[`README.md` line 201 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0FofEv0J9hlp8DDvA4:-N0dIRTY0v5hvQcflu9j:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L201)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"imports journey pattern metadata (not including actual stop point sequences) from the importer's database to the Jore 4 database"
</blockquote></details>

This is now fixed.
___
*[`README.md` line 202 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79#-N0Fp8ebC-OCvtxPcSv9:-N0dIZ9uEVi1gvhgbZrE:bt2vr0b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/a6d641ddb6ecdb048c3f98185582c6d3c63f33c1/README.md#L202)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"imports the sequence of scheduled stop point references for each journey pattern from the importer's database to the Jore 4 database"
</blockquote></details>

Fixed

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/79)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pallost)

**Pull request merged**
