### PR TITLE
Generate jOOQ query classes from Jore 4 database

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
- Add a properties which configure the Jore 4 database connection.
- Use executions for generating jOOQ query classes from the
  importer and Jore 4 databases.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: 0 of 58 files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[profiles/ci/config.properties, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3lEq1-GJOw6tPwS2j:-Mo3lEq1-GJOw6tPwS2k:bd1olr5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/ci/config.properties#L30)):*
> ```INI
> jore4.db.min.connections=0
> jore4.db.max.connections=5
> jore4.db.username=dbhasura
> ```

we do have an own user for importer. IIRC it's dbimporter / importerpassword. IIRC it should already have access to some db schemas but I might be wrong. At least there's this ticket here: https://github.com/HSLdevcom/jore4/issues/385
If the dbimporter user does not have access to the necessary schemas, please leave a comment here that you are temporarily using the hasura user while the permissions are fixed
___
*[profiles/ci/config.properties, line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mnpb-dwlrshuerQy:-Mo3mnpb-dwlrshuerQz:bju6hd) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/ci/config.properties#L56)):*
> ```INI
> 
> test.jore4.db.driver=org.postgresql.Driver
> test.jore4.db.url=jdbc:postgresql://localhost:6432/jore4e2e?stringtype=unspecified
> ```

here you seem to be using the exact same database for development and for running the tests. Is this intentional? Maybe you'd like to update the `importer-test-destination-database` service in your docker-compose to use a `jore4-postgres:azuremockdb` image that has all the jore4e2e and importer logical databases precreated... 
___
*[profiles/ci/config.properties, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mAns1SWfKdNSMoYf:-Mo3mAns1SWfKdNSMoYg:bq7sgtq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/ci/config.properties#L60)):*
> ```INI
> test.jore4.db.max.connections=5
> test.jore4.db.username=dbhasura
> test.jore4.db.password=hasurapassword
> ```

same as above, let's use the importer sql user or place a comment here that it's not yet possible
___
*[profiles/dev/config.properties, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mJPa1yENRfmuIPE2:-Mo3mJPa1yENRfmuIPE3:bq7sgtq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/dev/config.properties#L30)):*
> ```INI
> jore4.db.min.connections=0
> jore4.db.max.connections=5
> jore4.db.username=dbhasura
> ```

same as above, let's use the importer sql user or place a comment here that it's not yet possible
___
*[profiles/dev/config.properties, line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mMOUD2X_tzb1BzaW:-Mo3mMOUD2X_tzb1BzaX:bq7sgtq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/dev/config.properties#L59)):*
> ```INI
> test.jore4.db.min.connections=0
> test.jore4.db.max.connections=5
> test.jore4.db.username=dbhasura
> ```

same as above, let's use the importer sql user or place a comment here that it's not yet possible
___
*[profiles/prod/config.properties, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mW2S4aveh--3Ra_T:-Mo3mW2S4aveh--3Ra_U:bzy16o) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/prod/config.properties#L30)):*
> ```INI
> jore4.db.min.connections=0
> jore4.db.max.connections=5
> jore4.db.username=dbadmin
> ```

this profile is used within the production docker image. It should not have the url, username and password values prefilled for any db connection

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: 0 of 58 files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[profiles/ci/config.properties, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3lEq1-GJOw6tPwS2j:-Mo3qP_89syM-y35EL21:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/ci/config.properties#L30)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we do have an own user for importer. IIRC it's dbimporter / importerpassword. IIRC it should already have access to some db schemas but I might be wrong. At least there's this ticket here: https://github.com/HSLdevcom/jore4/issues/385
If the dbimporter user does not have access to the necessary schemas, please leave a comment here that you are temporarily using the hasura user while the permissions are fixed
</blockquote></details>

This is now fixed.
___
*[profiles/ci/config.properties, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mAns1SWfKdNSMoYf:-Mo3qQwy7ouqeF7DnGt1:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/ci/config.properties#L60)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

same as above, let's use the importer sql user or place a comment here that it's not yet possible
</blockquote></details>

This is now fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: 0 of 58 files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[profiles/prod/config.properties, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mW2S4aveh--3Ra_T:-Mo3t0uYA3UmJ0Z5Cszw:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/prod/config.properties#L30)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this profile is used within the production docker image. It should not have the url, username and password values prefilled for any db connection
</blockquote></details>

This is now fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: 0 of 58 files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[profiles/dev/config.properties, line 59 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo3mMOUD2X_tzb1BzaW:-Mo3t4N8DuwU2ALkd45x:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/0e2fee775f1a195522aea625cb0774653f9658f3/profiles/dev/config.properties#L59)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

same as above, let's use the importer sql user or place a comment here that it's not yet possible
</blockquote></details>

This is now fixed.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 1 of 58 files at r1, 1 of 57 files at r2, 58 of 58 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: all files reviewed, 8 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[pom.xml, line 469 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo8NLag05w_OXdYxK8R:-Mo8NLah9el6DYddRs3m:bay1wjs) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6a9e9bc3457b8642bcb61b5509c52b63aa504a48/pom.xml#L469)):*
> ```
>    | FLYWAY_SCHEMA_HISTORY.*
> ```

Hmmm...are all this relevant? Have you checked it? E.g. I don't believe there is `flyway_schema_history` table in Jore4 schemas. How about `spring`?
___
*[pom.xml, line 508 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo8a6Mw0cb1ilC9_d74:-Mo8a6Mw0cb1ilC9_d75:b-bdxvw1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6a9e9bc3457b8642bcb61b5509c52b63aa504a48/pom.xml#L508)):*
> ```
> .*\.infrastructure_node_location | .*\.infrastructure_node_projected_location
> ```

Hmmm... does there really exist field names like these in Jore4 database?

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: 53 of 60 files reviewed, 8 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[pom.xml, line 469 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo8NLag05w_OXdYxK8R:-Mo8ltkzEDHpSQSQp1Fq:b-o2x05e) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6a9e9bc3457b8642bcb61b5509c52b63aa504a48/pom.xml#L469)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>    | FLYWAY_SCHEMA_HISTORY.*
> ```

Hmmm...are all this relevant? Have you checked it? E.g. I don't believe there is `flyway_schema_history` table in Jore4 schemas. How about `spring`?
</blockquote></details>

Good catch. I removed unnecessary schema exclusions from both executions.
___
*[pom.xml, line 508 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50#-Mo8a6Mw0cb1ilC9_d74:-Mo8lztr0oQKcfDJDsod:bol7q5u) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6a9e9bc3457b8642bcb61b5509c52b63aa504a48/pom.xml#L508)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> .*\.infrastructure_node_location | .*\.infrastructure_node_projected_location
> ```

Hmmm... does there really exist field names like these in Jore4 database?
</blockquote></details>

No. I fixed the forced types.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: 52 of 60 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @jschummer)

**Review by jarkkoka — APPROVED** [review]
> Reviewed 7 of 7 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer)

**Pull request merged**
