### PR TITLE
Add hidden variant support to importer

### PR DESCRIPTION
**Pull request by Leitsi**
Resolves https://github.com/HSLdevcom/jore4/issues/1050

- - -
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Looks good! Please look at the few comments I added.

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-:-NJuLmKE-io-6fF5jbxf:b-e76rvf)* status: all files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJu2GtGD5RXuKsZRoXJ):*
Nice separation in version control.



_Code quote:_
```
- a5264ae: Fix docker reference table formatting

  Was not rendered correctly in eg. Github or VS Code.

- 9b64bd6: Clarify some details about local development environment

  Caused a bit of confusion, since the port is different depending on
  if running with local mvn or with docker.

- 4e39903: Update hasura image and generate jooq files

- 58fa3a3: Expose hidden variant from encoded identifier

- ac015d7: Import hidden variant to importer DB

- e67b146: Commit hidden variant to Jore 4 DB
```
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuLWHr-V8Td2GS-jHq:-NJuLWHt75VAY2ULr1oo:b-mmxnbx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L66)):*
> ```Java
>         }
>         catch (final NumberFormatException ex) {
>             return Optional.empty();
> ```

I'm not sure if  completely ignoring source data error without logging anything is a good idea. I see this is copied from the subsequent method below that also hides the exception.

Ideally, this code would throw an exception that the caller (`*Mapper` class) would handle as best seen (by logging an error). However, the following method should also need to be changed to work the same way.

But if the typing in the source database is such that a conversion error can never occur, then this piece of code is just fine, but a method comment should be added that it is the caller's responsibility to ensure that no conversion exceptions are hidden.



_Code quote:_
```Java
        catch (final NumberFormatException ex) {
            return Optional.empty();
        }
```
___
*[`src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java` line 126 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuIAkp9Xu6zodp6Xl8:-NJuIAkp9Xu6zodp6Xl9:b-z0difz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java#L126)):*
> ```Java
>                     "/sql/destination/drop_tables.sql",
>                     "/sql/destination/populate_lines.sql",
>                     "/sql/destination/populate_routes_staging.sql"
> ```

I'd rather have a non-null variant populated in this SQL file in order to test that hidden variant is actually handled correctly.



_Code quote:_
```Java
"/sql/destination/populate_routes_staging.sql"
```
___
*[`src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuH-UxEBfFpNIIVrY3:-NJuH-UxEBfFpNIIVrY4:b-7mftv7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java#L33)):*
> ```Java
> 
>     private static final Optional<Short> NO_HIDDEN_VARIANT = Optional.empty();
>     private static Optional<Short> hasHiddenVariant(int value) {
> ```

`final` qualifier missing (a style convention)



_Code quote:_
```Java
int
```

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102)* status: all files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJu2GtGD5RXuKsZRoXJ):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Nice separation in version control.
</blockquote></details>

:thumbsup: 
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuLWHr-V8Td2GS-jHq:-NJyRino74AN0euOy-LU:b-fl411w) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L66)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'm not sure if  completely ignoring source data error without logging anything is a good idea. I see this is copied from the subsequent method below that also hides the exception.

Ideally, this code would throw an exception that the caller (`*Mapper` class) would handle as best seen (by logging an error). However, the following method should also need to be changed to work the same way.

But if the typing in the source database is such that a conversion error can never occur, then this piece of code is just fine, but a method comment should be added that it is the caller's responsibility to ensure that no conversion exceptions are hidden.
</blockquote></details>

"Inspired" (copypasted) from the getOptionalLong method below indeed.

In the context where this is now used, the importer DB, where the field is nullable smallint. So, shouldn't be a problem.

As for Jore3 where this originates from, 6th digit of route/line id that is, only digits are used for hidden variant value (as since non-digits have other meaning). This was handled in EncodedIdentifier.

I would say we are safe here. I'll add comments on these though, good point.
___
*[`src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java` line 126 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuIAkp9Xu6zodp6Xl8:-NJyXCRz7hW4X1o7rlmB:bhpm9k) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/test/java/fi/hsl/jore/importer/feature/batch/route/support/RouteImportRepositoryTest.java#L126)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I'd rather have a non-null variant populated in this SQL file in order to test that hidden variant is actually handled correctly.
</blockquote></details>

Yep, good point, done.
___
*[`src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuH-UxEBfFpNIIVrY3:-NJyXFPLE_Slh9G6KBKd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

`final` qualifier missing (a style convention)
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-:-NJyifZA4qusWy1K0bbo:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuLWHr-V8Td2GS-jHq:-NJyh2Vv6zKpHtfDTAsP:b4zhvil) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L66)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

"Inspired" (copypasted) from the getOptionalLong method below indeed.

In the context where this is now used, the importer DB, where the field is nullable smallint. So, shouldn't be a problem.

As for Jore3 where this originates from, 6th digit of route/line id that is, only digits are used for hidden variant value (as since non-digits have other meaning). This was handled in EncodedIdentifier.

I would say we are safe here. I'll add comments on these though, good point.
</blockquote></details>

Ok, thanks for checking and adding the comment. :+1: 
___
*[`src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuH-UxEBfFpNIIVrY3:-NJyi1lwCN_CfiGuZNXy:bo1c2t2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java#L33)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I originally made the comment about the `int` parameter that was missing the `final` qualifier but there actually was two `final`s missing on this row. :)
___
*[`src/test/resources/sql/destination/populate_routes.sql` line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJyiRoE3t7pgrwKxfAr:-NJyiRoE3t7pgrwKxfAs:b-2rv4ci) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e5ab2b6eb073ed976298c203a5ec8ff45307ba0c/src/test/resources/sql/destination/populate_routes.sql#L9)):*
> ```TSQL
>         3,
>         '{"fi_FI": "Keskustori - Etelä-Hervanta vanha","sv_SE": "Central torget - Södra Hervanta gamla"}'
> );
> ```

EOL character is missing at the end. Could add at the same time.



_Code quote:_
```TSQL
  
```
___
*[`src/test/resources/sql/destination/populate_routes_staging.sql` line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJyidod8CVViwUEG8lU:-NJyidod8CVViwUEG8lV:b-2rv4ci) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e5ab2b6eb073ed976298c203a5ec8ff45307ba0c/src/test/resources/sql/destination/populate_routes_staging.sql#L8)):*
> ```TSQL
>         3,
>         '{"fi_FI": "Keskustori - Etelä-Hervanta","sv_SE": "Central torget - Södra Hervanta"}'
> );
> ```

EOL character is missing at the end. Could add at the same time.



_Code quote:_
```TSQL
 
```

**Review by Leitsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102)* status: all files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuLWHr-V8Td2GS-jHq:-NJyosGK4WqphmKNLz0f:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/main/java/fi/hsl/jore/importer/feature/batch/util/JdbcUtil.java#L66)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Ok, thanks for checking and adding the comment. :+1: 
</blockquote></details>

Done.
___
*[`src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJuH-UxEBfFpNIIVrY3:-NJyosyU9Pxx28r0d8_Y:biqmkal) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e67b146e97696a8922c291abf7f9cc652f163901/src/test/java/fi/hsl/jore/importer/feature/jore3/field/EncodedIdentifierTest.java#L33)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I originally made the comment about the `int` parameter that was missing the `final` qualifier but there actually was two `final`s missing on this row. :)
</blockquote></details>

Kappas. :ok_hand: 
___
*[`src/test/resources/sql/destination/populate_routes.sql` line 9 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJyiRoE3t7pgrwKxfAr:-NJyp6qk3mX5kgyYFPCB:bpwcxkn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e5ab2b6eb073ed976298c203a5ec8ff45307ba0c/src/test/resources/sql/destination/populate_routes.sql#L9)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

EOL character is missing at the end. Could add at the same time.
</blockquote></details>

Yep, was missing from these files so was going to leave it alone. CHanged IDEA settings to add those from now on, :ok_hand: 
___
*[`src/test/resources/sql/destination/populate_routes_staging.sql` line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102#-NJyidod8CVViwUEG8lU:-NJypDHuCuuv0WmC7y6d:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e5ab2b6eb073ed976298c203a5ec8ff45307ba0c/src/test/resources/sql/destination/populate_routes_staging.sql#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

EOL character is missing at the end. Could add at the same time.
</blockquote></details>

Done.

**Review by Leitsi — COMMENTED** [review]
> Reviewed 26 of 29 files at r1, 3 of 6 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102)* status: all files reviewed, 4 unresolved discussions (waiting on @jarkkoka)

**Review by jarkkoka — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

**Review by jarkkoka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Leitsi)

**Pull request merged**
