### PR TITLE
Replace Vavr lib with pure java utils

### PR DESCRIPTION
**Pull request by Huulivoide**
* Java Streams are now used for pipeline transformations.
* Immutability comes from using `Map.of()/List.of()/toList()` constructors.  Some places might generate a mutable collection, but it's ultimately up to the coder to not perform mutations, or assume mutable collections.
* Added a few helper functions:
  - `mapWithIndex`: Zip stream a iterable with int index
  - `concatToList`: Concat iterables to single list
  - `updateList`: Create a new List with value X at index Y
* Replaced Vectors with Lists. The Vector class came with Java 1.0. Java 1.2 introduced the Collections APIs, including List, ArrayList is the direct replacements for the Vector class. But generic List implementations are used here, as we do not want to mutate the data.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141)

### CODE REVIEW

**Review by culka — CHANGES_REQUESTED** [review]
> Reviewed 108 of 108 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141)* status: all files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/link_shape/LinkPointProcessor.java` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-LM_Dz5VdQ2vVTa9iI:-O-LM_Dz5VdQ2vVTa9iJ:b41k33b) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/7d1d91f804e7d40db17387b094af035a256e421a/src/main/java/fi/hsl/jore/importer/feature/batch/link_shape/LinkPointProcessor.java#L22)):*
> ```Java
>     private static LineString geometry(final LinkEndpoints endpoints, final List<JrPoint> items) {
>         final int srid = items.get(0).location().getSRID();
>         final List<Coordinate> coordinates = Stream.of(
> ```

We already use the google collections library in jore3 importer, so maybe it would be cleaner to use `Streams.concat` here instead of nested streams and flatmap.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RouteLinkConstructor.java` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-LOUDx7cqBL-q8ceBD:-O-LOUDx7cqBL-q8ceBE:b-6tmkyg) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/7b1e7703ca86738d22ef35de9c41df347166df7e/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RouteLinkConstructor.java#L23)):*
> ```Java
>     public static Vector<Jore3RouteLink> extractLinks(final RouteLinksAndAttributes entity) {
>         return entity.routeLinks()
>                 // The order number property is NOT guaranteed to be strictly incremental by 1,
> ```

This comment should be kept as it's important to know regarding the source data.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RoutePointConstructor.java` line 31 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-LOqQf3xhSqOQnuMAx:-O-LOqQf3xhSqOQnuMAy:bqxls2l) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/7b1e7703ca86738d22ef35de9c41df347166df7e/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RoutePointConstructor.java#L31)):*
> ```Java
>     public static Vector<Jore3RoutePoint> extractPoints(final RouteLinksAndAttributes entity) {
>         final Vector<Jore3RoutePoint> points = entity.routeLinks()
>                 // The order number property is NOT guaranteed to be strictly incremental by 1,
> ```

This comment should also be kept.
___
*[`src/main/java/fi/hsl/jore/importer/util/JoreCollectionUtils.java` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-LV6PvBIDo8OOB5sIG:-O-LV6PvBIDo8OOB5sIH:b-i9c2vt) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/7d1d91f804e7d40db17387b094af035a256e421a/src/main/java/fi/hsl/jore/importer/util/JoreCollectionUtils.java#L14)):*
> ```Java
> import java.util.stream.StreamSupport;
> 
> public class JoreCollectionUtils {
> ```

Looks really useful!

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141)* status: 105 of 108 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RouteLinkConstructor.java` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-LOUDx7cqBL-q8ceBD:-O-ZxuMOEJfyWULhpQxG:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/7b1e7703ca86738d22ef35de9c41df347166df7e/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RouteLinkConstructor.java#L23)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This comment should be kept as it's important to know regarding the source data.
</blockquote></details>

Done.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RoutePointConstructor.java` line 31 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-LOqQf3xhSqOQnuMAx:-O-ZxuzNBznk9Su73h5M:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/7b1e7703ca86738d22ef35de9c41df347166df7e/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RoutePointConstructor.java#L31)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

This comment should also be kept.
</blockquote></details>

Done.

**Review by jarkkoka — COMMENTED** [review]
Very thoughtful PR and definitely improves code quality! I left some small notes for you to consider.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-:-O-_5L3t5CC0hZlyfL5y:bpa7ch3)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @culka and @Huulivoide)

___
*[`-- commits` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_0OUQ9kEK5weiVxVo):*
The `Vector` class replaced is from Vavr, not `java.util` one.
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RoutePointConstructor.java` line 35 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_0uuwEnNJDbVx7a6F:-O-_0uux3XPWg8Jtv620:bf9m6ps) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/508cc68cfb7ae4eb09c2caf13347b7b548637ff4/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/RoutePointConstructor.java#L35)):*
> ```Java
>         final List<JrRouteLink> links = entity.routeLinks();
>         // The order number property is NOT guaranteed to be strictly incremental by 1,
>         // instead they can go 1, 2, 5, 10, 14, ... => reindex them from [0, 1, 2, ...]
> ```

Nice cleaning of comments. :+1: 
___
*[`src/main/java/fi/hsl/jore/importer/feature/batch/route_link/support/RouteStopPointImportRepository.java` line 89 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_1xhB0AV3t62Zprab:-O-_1xhB0AV3t62Zprac:bw4nbmf) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/508cc68cfb7ae4eb09c2caf13347b7b548637ff4/src/main/java/fi/hsl/jore/importer/feature/batch/route_link/support/RouteStopPointImportRepository.java#L89)):*
> ```Java
>                 .stream()
>                 .map(row -> RouteStopPointPK.of(row.value1()))
>                 .collect(Collectors.toSet());
> ```

Nothing needs to be changed here, but I would prefer to statically import the `Collectors.toSet()` method and use the more concise form `.collect(toSet())` because basically every Java coder knows which class the `toSet()` collector comes from.
___
*[`src/test/java/fi/hsl/jore/importer/feature/batch/place/support/PlaceImportRepositoryTest.java` line 59 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_4JQq6QMEZr02vmvd:-O-_4JQq6QMEZr02vmve:b-5e8uyq) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/508cc68cfb7ae4eb09c2caf13347b7b548637ff4/src/test/java/fi/hsl/jore/importer/feature/batch/place/support/PlaceImportRepositoryTest.java#L59)):*
> ```Java
>         @Test
>         public void whenNoStagedRowsAndCommit_thenReturnEmptyResult() {
>             assertThat(importRepository.commitStagingToTarget(), is(Collections.emptyMap()));
> ```

There is no need to change anything here, but I would prefer to statically import the `Collections.emptyMap()` method and use the more concise form `is(emptyMap())` because basically every Java coder knows which class the `emptyMap()` method comes from.
___
*[`src/test/java/fi/hsl/jore/importer/feature/jore4/repository/Jore4RouteGeometryRepositoryTest.java` line 77 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_4mbr1bfdoBy3dF-k:-O-_4mbr1bfdoBy3dF-l:bfwrza1) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/508cc68cfb7ae4eb09c2caf13347b7b548637ff4/src/test/java/fi/hsl/jore/importer/feature/jore4/repository/Jore4RouteGeometryRepositoryTest.java#L77)):*
> ```Java
>             @BeforeEach
>             void createInput() {
>                 final java.util.List<Jore4RouteInfrastructureLink> infrastructureLinks =
> ```

No need to use fully qualified class name here since `java.util.List` is already imported.
___
*[`src/test/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilderTest.java` line 65 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_4xHqCjR7RcwRp6eN:-O-_4xHqCjR7RcwRp6eO:b-xjedtr) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/508cc68cfb7ae4eb09c2caf13347b7b548637ff4/src/test/java/fi/hsl/jore/importer/feature/mapmatching/dto/request/MapMatchingRequestBuilderTest.java#L65)):*
> ```Java
>         void shouldReturnMapMatchingRequestWithCorrectRouteId() {
>             final MapMatchingRequestDTO request =
>                     MapMatchingRequestBuilder.createMapMatchingRequest(routeGeometryInput, Collections.emptyList());
> ```

There is no need to change anything here, but I would prefer to statically import the `Collections.emptyList()` method and use the more concise form `emptyList()` because basically every Java coder knows which class that method comes from.
___
*[`src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingServiceTest.java` line 50 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-O-_58w7ES0iLt_RVemf:-O-_58w88QaA7AiDUI2C:b-4jwbtn) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/508cc68cfb7ae4eb09c2caf13347b7b548637ff4/src/test/java/fi/hsl/jore/importer/feature/mapmatching/service/MapMatchingServiceTest.java#L50)):*
> ```Java
> 
>     private ImporterRouteGeometry routeGeometryInput;
>     private java.util.List<ImporterRoutePoint> routePointsInput;
> ```

Package qualifier is extraneous here.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 34 of 34 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141)* status: all files reviewed, 9 unresolved discussions (waiting on @culka and @Huulivoide)

**Review by culka — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/141#-:-O-_Pffk2HuXt_hlwWLF:bg7igkv)* status: all files reviewed, 7 unresolved discussions (waiting on @Huulivoide)

**Pull request merged**
