### PR TITLE
Rename destination data source to importer data source

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
This commit changes the name of the destination data source
because the destination database of the import process is not
the database which contains the data imported from Jore 3. The
destination database of the import process is the Jore 4 database.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[profiles/ci/config.properties, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43#-MnUbYAwBjNpnKea-wMC:-MnUbYAwBjNpnKea-wMD:b-1qlpgi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/34d4b38ad19182b87be36b3e4d63bc69a8c3ea59/profiles/ci/config.properties#L10)):*
> ```INI
> 
> # Datasource settings for the importer Postgresql database
> importer.db.driver=org.postgresql.Driver
> ```

please also mark these changes in the README.md docker reference section

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[README.md, line 78 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43#-MnUhuax1Q6b6EwgDCXD:-MnUhuax1Q6b6EwgDCXE:b-7wv9hq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/54f4a3e1d4d4ab42a0c117c9ed5a18b43c2659ad/README.md#L78)):*
> ```Markdown
> | source.db.username      | SOURCE_DB_USERNAME      | source-db-username      | sa                                                                               | Username for the source database                                                 |
> | source.db.password      | SOURCE_DB_PASSWORD      | source-db-password      | ****                                                                             | Password for the source database                                                 |
> | importer.db.url         | IMPORTER_DB_URL         | importer-db-url         | jdbc:postgresql://localhost:5432/devdb?stringtype=unspecified                    | The jdbc url of the destination JORE4 PostgreSQL database                        |
> ```

this description is not correct anymore as this jdbc url is for the importer's own dedicated postgres database

could you also edit the examples a tiny bit that it's not `devdb` anymore but `importerdb`?

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[README.md, line 78 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43#-MnUhuax1Q6b6EwgDCXD:-MnUjMkJ5qlgrBWEmH-V:b-ybyka7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/54f4a3e1d4d4ab42a0c117c9ed5a18b43c2659ad/README.md#L78)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this description is not correct anymore as this jdbc url is for the importer's own dedicated postgres database

could you also edit the examples a tiny bit that it's not `devdb` anymore but `importerdb`?
</blockquote></details>

Fixed. The database name hasn't changed (or at least I haven't changed it). I can change it if we figure out a better name for it.
___
*[profiles/ci/config.properties, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43#-MnUbYAwBjNpnKea-wMC:-MnUjLtq0Zhkg8T4BrLV:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/34d4b38ad19182b87be36b3e4d63bc69a8c3ea59/profiles/ci/config.properties#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please also mark these changes in the README.md docker reference section
</blockquote></details>

Fixed.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/43)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @jarkkoka and @jschummer)

**Pull request merged**
