### PR TITLE
Ci integration

### PR DESCRIPTION
**Pull request by lassemaatta**
Next batch of changes, mostly related to testing:
- Use MS SQL in tests instead of H2
- Use github actions to run tests

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3)

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[docker/mssql_init/populate.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYisY_iDLcZVnQYgPoJ:-MYisY_j3cgX-vt0Qwq1:b-wg9w8l) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/populate.sql#L11)):*
> ```TSQL
> GO
> --
> -- Create jr_solmu
> ```

I'm not 100% sure if it's a good idea to create these tables here. It makes the tests faster (by some unknown amount), because we don't need to drop and recreate the tables every time, but also requires that the dockerized database is recreated (using the `dev_deps.sh` script) when new tables are added (jr_linja, jr_...)

**Review by pallost — COMMENTED** [review]
personally, I'd leave the pre-populating of the database schema as it needs a lot of dependencies (like the wait-for scripts) and maintenance (if the imported schemas are extended) unless it speeds up the unit tests a lot

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-:-MYnv_pw1QKH6_DQZVa6:b-wuuirh)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[.github/workflows/ci.yml, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYnr0E99-CX2gUWbx_O:-MYnr0E99-CX2gUWbx_P:b-x3s6gd) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/.github/workflows/ci.yml#L3)):*
> ```YAML
> name: Java CI
> 
> on: [ push ]
> ```

did you mean to also run this workflow for pull requests?
___
*[docker/Dockerfile_mssql, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYnsLWT1hdxbyQBLsFn:-MYnsLWT1hdxbyQBLsFo:b5elb13) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/Dockerfile_mssql#L14)):*
> ```
> 
> COPY ./mssql_init/ /usr/src/app
> COPY ./wait-for-it.sh /usr/src/app/
> ```

it's not a good practice to have these kind of wait-for scripts within the docker images as waiting for a dependency belongs to the running environment and not the image itself. The docker-compose healthcheck parameter can be used to know when the depended service is ready. Here's an example for usage: https://github.com/peter-evans/docker-compose-healthcheck

nevermind, I see you only use this script internally, within the image, not to check for the readiness of the dependencies. Then it's fine if there's no better to run migrations are the server startup
___
*[docker/wait-for-it.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYns2g58rHE2Qoc1fRH:-MYns2g58rHE2Qoc1fRI:b-ye0rf6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/wait-for-it.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # Use this script to test if a given TCP host/port are available
> ```

it's a nice gesture to mark the source when you take some code from somewhere. It's also useful when trying to fix the issues related to it ;)
___
*[docker/mssql_init/populate.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYisY_iDLcZVnQYgPoJ:-MYntZk44mgmawnZ53IB:b-ky7212) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/populate.sql#L11)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

I'm not 100% sure if it's a good idea to create these tables here. It makes the tests faster (by some unknown amount), because we don't need to drop and recreate the tables every time, but also requires that the dockerized database is recreated (using the `dev_deps.sh` script) when new tables are added (jr_linja, jr_...)
</blockquote></details>

I think technically you only need to create these table once also for your unit tests, then it's enough to just to use TRUNCATE to clear all the data. It probably does not slow the tests down much but would need less maintenance. Thoughts?
___
*[docker/mssql_init/wait_and_populate.sh, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYnuSyR91T33OZcwFO-:-MYnuSySDMQziLzLoTmK:bi4b157) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/wait_and_populate.sh#L15)):*
> ```Shell
> echo "Populating DB with sample data.."
> 
> /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -d master -i populate.sql
> ```

damn, this is ugly... I'm sad that there's no built-in solution for this like in the postgresql docker image...

**Review by lassemaatta — COMMENTED** [review]
Creating the database tables shouldn't take very long, it's starting the MS SQL database that takes a relatively long time and requires those nasty wait-for scripts. And that needs to happen only once when starting the dev dependencies (ms sql + postgres).

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-:-MYnzSbE5JhkZD8gTmz3:b-3n4m9w)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @lassemaatta, and @pallost)

___
*[docker/wait-for-it.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYns2g58rHE2Qoc1fRH:-MYnxJaH2dc_j12FJLXs:b-r0z42) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/wait-for-it.sh#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's a nice gesture to mark the source when you take some code from somewhere. It's also useful when trying to fix the issues related to it ;)
</blockquote></details>

It's actually mentioned in the commit message, but I can add it here too.
___
*[docker/mssql_init/populate.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYisY_iDLcZVnQYgPoJ:-MYnxOG13ICVj19eP_ai:b-lapnwe) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/populate.sql#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think technically you only need to create these table once also for your unit tests, then it's enough to just to use TRUNCATE to clear all the data. It probably does not slow the tests down much but would need less maintenance. Thoughts?
</blockquote></details>

Technically yes, but that might require some additional logic in the test setup. The `@Sql(scripts = "some_file.sql")` approach doesn't support "run this SQL for the whole test suite once", so I'd have to do it manually somehow. I can try to figure out how it could be implemented.
___
*[docker/mssql_init/wait_and_populate.sh, line 15 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYnuSyR91T33OZcwFO-:-MYnyi07EzJ2B4X_Oq-x:b-8xtlpb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/wait_and_populate.sh#L15)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

damn, this is ugly... I'm sad that there's no built-in solution for this like in the postgresql docker image...
</blockquote></details>

Yeah. I couldn't find any reliable way to figure out if MS SQL is running, other than checking port 1433. And even then it doesn't guarantee that it's actually ready to accept connections. And the delay naturally depends on the test runner performance, e.g. on my own machine it mostly worked without the "sleep 5s" but during CI it would almost always fail without it :(

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @lassemaatta, and @pallost)

___
*[.github/workflows/ci.yml, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYnr0E99-CX2gUWbx_O:-MYo-5Iq4Ku5W_rlwMG0:b-f9nit2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/.github/workflows/ci.yml#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

did you mean to also run this workflow for pull requests?
</blockquote></details>

Umm.. I'm not sure. I don't know how github actions work or how we should use them :)

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @lassemaatta, and @pallost)

___
*[docker/mssql_init/populate.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYisY_iDLcZVnQYgPoJ:-MYo6C86DCohcwzw7HfJ:b9x90wn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/populate.sql#L11)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Technically yes, but that might require some additional logic in the test setup. The `@Sql(scripts = "some_file.sql")` approach doesn't support "run this SQL for the whole test suite once", so I'd have to do it manually somehow. I can try to figure out how it could be implemented.
</blockquote></details>

For some reason running the "CREATE TABLE" stuff in the tests just results in an "incorrect syntax" error from the MS SQL JDBC driver :(

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @lassemaatta, and @pallost)

___
*[.github/workflows/ci.yml, line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYnr0E99-CX2gUWbx_O:-MYs0-ZR0vow9-A_gzm5:b-beteyv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/.github/workflows/ci.yml#L3)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Umm.. I'm not sure. I don't know how github actions work or how we should use them :)
</blockquote></details>

If I understand the "on:" thing correctly, then `on: [ push ]` is what I want. That is, any time any commit is pushed to any branch -> run CI. Just using `pull_request` would only run the CI when a pull request is created ("opened, synchronize or reopened"), which I don't really care about.

**Review by pallost — APPROVED** [review]
I really don't like the wait-for scripts at all, but as they are only used here for the test database, I guess I can let it go...

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-:-MYxW0jDCYTDCs0VObyY:boj1elk)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @lassemaatta)

___
*[docker/mssql_init/populate.sql, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-MYisY_iDLcZVnQYgPoJ:-MYxV_6J8_3VhJtbR0lQ:b-ifqiuf) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/699d53a82ebf104f1439f2123bba83bf6ac6875b/docker/mssql_init/populate.sql#L11)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

For some reason running the "CREATE TABLE" stuff in the tests just results in an "incorrect syntax" error from the MS SQL JDBC driver :(
</blockquote></details>

weird stuff... I do see that you used `USE testsourcedb;`, so it should've worked...

**Review by pallost — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/3#-:-MYxY3IL5RCqKsClAYQS:bnfp4nl)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @lassemaatta)

**Pull request merged**
