### PR TITLE
Docker compose refactor

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24)

### CODE REVIEW

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[pom.xml, line 186 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24#-Mj3enltBl8gfoJck45n:-Mj3enltBl8gfoJck45o:bnci400) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/b8ae30544425d9cbd8c23eb18eb2d1380eb90626/pom.xml#L186)):*
> ```XML
>             <build>
>                 <filters>
>                     <filter>profiles/${build.profile.id}/config.${user.name}.properties</filter>
> ```

The value of the `filter` property should be replaced with: `${build.property.file}`. This way the used property file is specified only once when the value of the `build.property.file` property is set.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[pom.xml, line 186 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24#-Mj3enltBl8gfoJck45n:-Mj47gMw-p8FSspXgPFU:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/b8ae30544425d9cbd8c23eb18eb2d1380eb90626/pom.xml#L186)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The value of the `filter` property should be replaced with: `${build.property.file}`. This way the used property file is specified only once when the value of the `build.property.file` property is set.
</blockquote></details>

Done.

**Review by jschummer — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24#-:-Mj8Fc4F8Z7tcrt0N7Pa:bg7igkv)* status: 0 of 14 files reviewed, 1 unresolved discussion (waiting on @jarkkoka and @pkainulainen-vincit)

**Review by jarkkoka — APPROVED** [review]
> Reviewed 13 of 14 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/24)* status: all files reviewed, 1 unresolved discussion (waiting on @pkainulainen-vincit)

**Pull request merged**
