### PR TITLE
Add Coding Conventions section to README

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnVFJyE1ZjIgbfQExk3:-MnVFJyE1ZjIgbfQExk4:b-88s9hw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3b360bcf6d05b884768b87f475e2da59c240a75/README.md#L7)):*
> ```Markdown
> ## Coding Conventions
> 
> This section identifies the coding conventions which you must follow when you are writing code for 
> ```

Trailing spaces
___
*[README.md, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnVF2Zi8KEpjiPTAtea:-MnVF2Zi8KEpjiPTAteb:b-a00vd8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3b360bcf6d05b884768b87f475e2da59c240a75/README.md#L11)):*
> ```Markdown
> 
> * You must use the `final` keyword when you declare fields, local variables, constructor arguments, or method parameters
>   whose value cannot be changed after it has been assigned for the first time. This coding convention must be followed
> ```

"This coding convention must be followed when you are writing either production or test code." 
Does this sentence add any additional information? We already said that
"This section identifies the coding conventions which you must follow when you are writing code for this project."
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnVFLDU73n3D1b1ZmKE:-MnVFLDU73n3D1b1ZmKF:b-bovqw7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3b360bcf6d05b884768b87f475e2da59c240a75/README.md#L13)):*
> ```Markdown
>   whose value cannot be changed after it has been assigned for the first time. This coding convention must be followed
>   when you are writing either production or test code.
> * When you add new fields to entities or data transfer objects, you must follow these 
> ```

Trailing spaces. Maybe you could set your editor to remove these automatically.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnVF2Zi8KEpjiPTAtea:-MnVK6Fq4fvMPv-U9tap:b-fivelp) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3b360bcf6d05b884768b87f475e2da59c240a75/README.md#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"This coding convention must be followed when you are writing either production or test code." 
Does this sentence add any additional information? We already said that
"This section identifies the coding conventions which you must follow when you are writing code for this project."
</blockquote></details>

I moved this section: "either production or test code" to the beginning of the README. The reason why I think its essential to mention this is this: 

I think that using the `final` keyword in test code doesn't add any value to the test in question.  Also, I know there are several other people who think like I do => It's important to mention that you must follow these guidelines even in test code. This also makes the review process much faster because PR's won't get stuck because of code style arguments.
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnVFLDU73n3D1b1ZmKE:-MnVLSdr1aMBNi9L7gRe:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3b360bcf6d05b884768b87f475e2da59c240a75/README.md#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Trailing spaces. Maybe you could set your editor to remove these automatically.
</blockquote></details>

Fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @tk-vincit)

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnVFJyE1ZjIgbfQExk3:-MnVLfH91UHc40OmdlPx:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e3b360bcf6d05b884768b87f475e2da59c240a75/README.md#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Trailing spaces
</blockquote></details>

Fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnW9mXC4CqmpRGrvvm_:-MnZUu7JEddVlorNOEvo:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6c9fe6532ce4eca7b93a55f0b35ec92e90e49cc0/README.md#L8)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> for this project. These coding conventions are described in the following:
> 
> ```

There are a couple of conventions that you did not mention.
- One is that for each Java package one should add a `package-info.java` file where package name is annotated as seen below.
```
@NonNullApi
@NonNullFields

fi.hsl.jore.foo.bar

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
```
- Tag nullable method parameters and return values with `@Nullable`. Non-null parameters and return values should not be annotated because they are already covered by `package-info.java`.
- Use only immtable DTO's by introducing interfaces annotated with `org.immutables` annotations.
</blockquote></details>

Fixed.
___
*[README.md, line 14 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnW7khE8xesi8mPYsBt:-MnZVPXM7DTWAU0yP0pn:bh768m4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/6c9fe6532ce4eca7b93a55f0b35ec92e90e49cc0/README.md#L14)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> String
> ```

`String` is not a primitive since a `String` reference may be null.
</blockquote></details>

I rephrased that coding convention.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: all files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 18 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-Mn_fT6i3k97dH0QRAU6:-Mn_fT6i3k97dH0QRAU7:b-8eqfav) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/40493b232ebb990ef7e29630352e6c5cd8b2932b/README.md#L18)):*
> ```
> should not be annotated because they are already covered by 
> ```

"are not needed to be annotated because non-nullness is the default scheme imposed by"

My original comment text was a bit clumsy to be reused here.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 18 at r4](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-Mn_fT6i3k97dH0QRAU6:-Mna0wNl7Xw87SfBoIfi:b7mwbrq) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/40493b232ebb990ef7e29630352e6c5cd8b2932b/README.md#L18)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> should not be annotated because they are already covered by 
> ```

"are not needed to be annotated because non-nullness is the default scheme imposed by"

My original comment text was a bit clumsy to be reused here.
</blockquote></details>

I rephrased that sentence.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: all files reviewed, 8 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 14 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnjZ6WG6Nib3a16lDU0:-MnjZ6WG6Nib3a16lDU1:b-lvq6i3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c60f8777b5e75824aa94c2fe978ec0ef3bb0e9d2/README.md#L14)):*
> ```
>   If the field contains a string, set its type to `String`.
> ```

Hmmm...I think this is something considered pretty self-evident and could be removed. What would be the alternatives in Java realistically? (this is not C++)

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

___
*[README.md, line 14 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44#-MnjZ6WG6Nib3a16lDU0:-Mnjfw5cD6ayNG6DKzEh:b-886gsx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c60f8777b5e75824aa94c2fe978ec0ef3bb0e9d2/README.md#L14)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>   If the field contains a string, set its type to `String`.
> ```

Hmmm...I think this is something considered pretty self-evident and could be removed. What would be the alternatives in Java realistically? (this is not C++)
</blockquote></details>

Fixed

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/44)* status: all files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, @pkainulainen-vincit, and @tk-vincit)

**Pull request merged**
