### PR TITLE
Update ci workflow

### PR DESCRIPTION
**Pull request by culka**
Use e2e test action from tools repo
Unify CI to run jobs under one workflow

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138)

### CODE REVIEW

**Review by niknii-vincit — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @culka)

___
*[`.github/workflows/cd.yml` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138#-NzDNv7u5d3FnhE-7pI4:-NzDNv7u5d3FnhE-7pI5:b2w9xkn) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/9e317c8fa648b5dc9e9883b6a332d13703baf170/.github/workflows/cd.yml#L13)):*
> ```YAML
>   run_java_tests:
>     name: Run Java tests
>     uses: ./.github/workflows/java-tests.yml
> ```

We don't need these anywhere else, right? Just making sure that we're note repeating these everywhere else as well :smile: 
___
*[`.github/workflows/java-tests.yml` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138#-NzDMx92DfwKVtHLLLN1:-NzDMx92DfwKVtHLLLN2:b-ewcrfd) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/9e317c8fa648b5dc9e9883b6a332d13703baf170/.github/workflows/java-tests.yml#L4)):*
> ```YAML
> 
> on:
>   # this workflow is only called by others, won't be executed on itself
> ```

Great that you commented here, will be useful in the future!

**Review by culka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @niknii-vincit)

___
*[`.github/workflows/cd.yml` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138#-NzDNv7u5d3FnhE-7pI4:-NzDORnj9UrkRJN3Ci8B:b-wbqehg) ([raw file](https://github.com/HSLdevcom/jore4-jore3-importer/blob/9e317c8fa648b5dc9e9883b6a332d13703baf170/.github/workflows/cd.yml#L13)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

We don't need these anywhere else, right? Just making sure that we're note repeating these everywhere else as well :smile:
</blockquote></details>

There are differences in the unit test runs between repositories, I don't think they should use a common action.

**Review by niknii-vincit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138#-:-NzDkVzKCCizCxu_Cuw_:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by niknii-vincit — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @culka)

**Review by niknii-vincit — APPROVED** [review]
:shipit: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-jore3-importer/138#-:-NzRrwrm3ZmGMsbijAMn:bizlbj6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @culka)

**Pull request merged**
