### PR TITLE
Add HTTP API for starting jobs

### PR DESCRIPTION
**Pull request by lassemaatta**
- Use allowStartIfComplete(true) on steps so that
  we can rerun the same job multiple times

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[README.md, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-Mbjn5Q56OtcbV4Pk_nv:-Mbjn5Q56OtcbV4Pk_nw:b-nj2inb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/README.md#L60)):*
> ```Markdown
> ```shell
> $ curl  http://localhost:8080/job/import/status/
> {"batchStatus":"FAILED","exitCode":"FAILED","exitDescription":"<here's a really long Java stack trace>","startTime":"2021-04-09T08:39:47.698Z","endTime":"2021-04-09T08:41:17.761Z"}
> ```

I couldn't find the actual code snippet what the exitDescription contains, but it should rather just return a generic error message and then the stack trace could go to logs

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/api/dto/JobStatus.java, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjncoZ05oLCIU6Ppje:-MbjncoZ05oLCIU6Ppjf:bt989w0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/main/java/fi/hsl/jore/importer/feature/api/dto/JobStatus.java#L20)):*
> ```Java
>     BatchStatus batchStatus();
> 
>     Optional<String> exitCode();
> ```

shouldn't the exitCode be mandatory field...?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @lassemaatta)

___
*[src/test/java/fi/hsl/jore/importer/BatchIntegrationTest.java, line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjnrI3CXAkSTtx5BVr:-MbjnrI3CXAkSTtx5BVs:bpc3dir) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/test/java/fi/hsl/jore/importer/BatchIntegrationTest.java#L47)):*
> ```Java
>             launcher.afterPropertiesSet();
>         } catch (final Exception e) {
>             LOG.error("Failed to construct JobLauncher for tests");
> ```

should you also log the exception object itself?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @lassemaatta)

___
*[README.md, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjoYK6D6LEs5wNd3yw:-MbjoYK6D6LEs5wNd3yx:b-olr908) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/README.md#L35)):*
> ```Markdown
> ```shell
> $ curl -X POST http://localhost:8080/job/import/start/
> {"batchStatus":"STARTING","exitCode":"UNKNOWN","exitDescription":null,"startTime":null,"endTime":null}
> ```

would it be easy to add an auto-generated UUID field to each job run to be able to easily identity the executions? I know the startTime is also unique, but a UUID would be easier to use as an identitier

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @lassemaatta)

___
*[src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java, line 146 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjozWV6bH2cazyuYzm:-MbjozWV6bH2cazyuYzn:b-458tgo) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java#L146)):*
> ```Java
>     @Test
>     public void whenStartingJobWhileRunning_thenReturnCurrentStatus() throws Exception {
>         final Instant startTime = Instant.parse("2021-04-06T14:33:00.00Z");
> ```

could you also add a test that fails with an error?

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: all files reviewed, 6 unresolved discussions (waiting on @lassemaatta)

___
*[src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java, line 94 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbkaXCA4JmupAXIbiGx:-MbkaXCA4JmupAXIbiGy:b-900e81) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java#L94)):*
> ```
> "application/json"
> ```

Media type constants are defined and can also be found from Spring web dependency libraries e.g. MediaType.APPLICATION_JSON_VALUE.

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: all files reviewed, 6 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[README.md, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjoYK6D6LEs5wNd3yw:-MboQg5Y9RHEHEoLQh34:b-d1urno) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/README.md#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

would it be easy to add an auto-generated UUID field to each job run to be able to easily identity the executions? I know the startTime is also unique, but a UUID would be easier to use as an identitier
</blockquote></details>

https://imgflip.com/i/5cqvt7
___
*[README.md, line 60 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-Mbjn5Q56OtcbV4Pk_nv:-MboLYOZ9ZVqvf_hqnzL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/README.md#L60)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I couldn't find the actual code snippet what the exitDescription contains, but it should rather just return a generic error message and then the stack trace could go to logs
</blockquote></details>

Done.
___
*[src/main/java/fi/hsl/jore/importer/feature/api/dto/JobStatus.java, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjncoZ05oLCIU6Ppje:-MboIuts0gvAksxh0FAS:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/main/java/fi/hsl/jore/importer/feature/api/dto/JobStatus.java#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

shouldn't the exitCode be mandatory field...?
</blockquote></details>

Done.
___
*[src/test/java/fi/hsl/jore/importer/BatchIntegrationTest.java, line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjnrI3CXAkSTtx5BVr:-MboGcKh3t50OUlycRca:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/test/java/fi/hsl/jore/importer/BatchIntegrationTest.java#L47)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should you also log the exception object itself?
</blockquote></details>

Done.
___
*[src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java, line 94 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbkaXCA4JmupAXIbiGx:-MboH46-0wtZNg81MZLV:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java#L94)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> "application/json"
> ```

Media type constants are defined and can also be found from Spring web dependency libraries e.g. MediaType.APPLICATION_JSON_VALUE.
</blockquote></details>

Done.
___
*[src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java, line 146 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8#-MbjozWV6bH2cazyuYzm:-MboQj9r06fONTyW3O1q:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/65629349073feb815c8f306a60621bbbacbe85cc/src/test/java/fi/hsl/jore/importer/feature/api/JobControllerTest.java#L146)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could you also add a test that fails with an error?
</blockquote></details>

Done

**Review by jarkkoka — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/8)* status: all files reviewed, 5 unresolved discussions (waiting on @pallost)

**Pull request merged**
