### PR TITLE
Configure the scheduled stop point export flow

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
- Create a Spring Batch flow which exports scheduled
  stop points to the Jore4 database.
- Write new integration tests.
- Fix existing integration tests.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
just minor remarks or questions

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-:-MpCDxsj-6y50f8R2A8A:b-2v5hxl)* status: all files reviewed, 7 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC5x1o9_g_o_uKpaT1:-MpC5x1pDzIXv8qXy-tV:b-sdhbz2) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L19)):*
> ```
> @Profile(Profiles.STANDARD_DATABASE)
> ```

Use annotation: `@StandardDatabase`
___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpCAKYlEs7QhuZqHx37:-MpCAKYlEs7QhuZqHx38:bnjlw22) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L23)):*
> ```
> digiroad.stop.csv.file.path
> ```

There does not exist a configuration property with the same name in `profiles/prod/config.properties` or `src/main/resources/*.properties`. I think that there should be a placeholder already.
___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC644Q1WM1GdVyR6DB:-MpC644Q1WM1GdVyR6DC:b-j5mihu) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L29)):*
> ```
>  @Profile(Profiles.TEST_DATABASE)
> ```

Use annotation: `@TestDatabase`
___
*[src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java, line 517 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7P3W1xj-8Ez89Qy3:-MpC7P3W1xj-8Ez89Qy4:b5ppact) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L517)):*
> ```
> exportt
> ```

`export`
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7lLA7sAdPGlvL2Sk:-MpC7lLA7sAdPGlvL2Sl:b-ogrj0w) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L28)):*
> ```
> @Autowired
> ```

Probably not used
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 40 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7uAc2n55DUnDoEbu:-MpC7uAc2n55DUnDoEbv:bmqc79i) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L40)):*
> ```
> @PostConstruct
> ```

Is `@PostConstruct` working as expected after `Service` annotation was removed?
___
*[src/test/java/fi/hsl/jore/importer/config/jobs/ExportScheduledStopPointsStepTest.java, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC8K06CudYRGKUZXll:-MpC8K06CudYRGKUZXlm:b-yq0188) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/test/java/fi/hsl/jore/importer/config/jobs/ExportScheduledStopPointsStepTest.java#L38)):*
> ```
> TransmodelScheduledStopPointDirection.
> ```

Would be nicer if the enum value was statically imported since the class name is repeated two times on the row.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53)* status: 10 of 15 files reviewed, 7 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC5x1o9_g_o_uKpaT1:-MpFeBip1iC3A9lo2YJ-:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L19)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> @Profile(Profiles.STANDARD_DATABASE)
> ```

Use annotation: `@StandardDatabase`
</blockquote></details>

This is now fixed.
___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpCAKYlEs7QhuZqHx37:-MpFtWXz1f2-ZWw6vEXO:b-uiigpw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> digiroad.stop.csv.file.path
> ```

There does not exist a configuration property with the same name in `profiles/prod/config.properties` or `src/main/resources/*.properties`. I think that there should be a placeholder already.
</blockquote></details>

These configuration properties were added on a previous commit and they are already present at the main branch. See:

https://github.com/HSLdevcom/jore4-jore3-importer/blob/main/profiles/prod/config.properties 
https://github.com/HSLdevcom/jore4-jore3-importer/blob/main/src/main/resources/application.properties
___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 29 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC644Q1WM1GdVyR6DB:-MpFeDIs5m8wotxnKuMB:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L29)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>  @Profile(Profiles.TEST_DATABASE)
> ```

Use annotation: `@TestDatabase`
</blockquote></details>

This is now fixed.
___
*[src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java, line 517 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7P3W1xj-8Ez89Qy3:-MpFeLpo-SGPWNxqhVtE:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/jobs/JobConfig.java#L517)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> exportt
> ```

`export`
</blockquote></details>

This is now fixed.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7lLA7sAdPGlvL2Sk:-MpFeStb8q1tJf-nUWE7:bjc8bfv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L28)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> @Autowired
> ```

Probably not used
</blockquote></details>

True. Removed that annotation.
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 40 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7uAc2n55DUnDoEbu:-MpFjHz40BihytE1tH4O:b66m7ld) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L40)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> @PostConstruct
> ```

Is `@PostConstruct` working as expected after `Service` annotation was removed?
</blockquote></details>

Yes. By the way, his comment helped me to find another bug (the correct file path wasn't passed to the constructor and the component couldn't read the CSV file). This bug is now fixed as well. So, thank you for asking this question.
___
*[src/test/java/fi/hsl/jore/importer/config/jobs/ExportScheduledStopPointsStepTest.java, line 38 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC8K06CudYRGKUZXll:-MpFeeXUA9vV5ok9xRsA:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/test/java/fi/hsl/jore/importer/config/jobs/ExportScheduledStopPointsStepTest.java#L38)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> TransmodelScheduledStopPointDirection.
> ```

Would be nicer if the enum value was statically imported since the class name is repeated two times on the row.
</blockquote></details>

This is now fixed.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpCAKYlEs7QhuZqHx37:-MpGATcg4IWQ0sCm6YGH:bhuiq81) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/config/DigiroadServiceConfig.java#L23)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

These configuration properties were added on a previous commit and they are already present at the main branch. See:

https://github.com/HSLdevcom/jore4-jore3-importer/blob/main/profiles/prod/config.properties 
https://github.com/HSLdevcom/jore4-jore3-importer/blob/main/src/main/resources/application.properties
</blockquote></details>

Ok, sorry, my bad.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 44 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpGBHtp69IK8LVhvnNM:-MpGBHtp69IK8LVhvnNN:bprprwv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f0d8de64ff2e23691131ad61de02f20ba905ef51/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L44)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         Optional<String> elyNumber = jore3Stop.elyNumber();
>         if (elyNumber.isEmpty() || elyNumber.get().isEmpty()) {
>             LOGGER.debug("Jore 3 stop with id: {} isn't processed any further because it has no ely number",
>                     jore3Stop.externalId().value()
>             );
>             return null;
>         }
>
>         final int nationalId = Integer.parseInt(elyNumber.get());
> ```
</details>


I'd prefer more idiomatic Java:

```
        final String elyNumber = jore3Stop.elyNumber()
                .filter(str -> !str.isEmpty())
                .orElseGet(() -> {
                    LOGGER.debug("Jore 3 stop with id: {} isn't processed any further because it has no ely number",
                            jore3Stop.externalId().value()
                    );
                    return null;
                });

        final int nationalId = Integer.parseInt(elyNumber);
```
___
*[src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java, line 40 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpC7uAc2n55DUnDoEbu:-MpGAyexEgRGXz5tpaw_:bwl0wfd) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/fc6119854a32965da0bf1ef01bc6d07e5b676deb/src/main/java/fi/hsl/jore/importer/feature/digiroad/service/CsvDigiroadStopService.java#L40)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Yes. By the way, his comment helped me to find another bug (the correct file path wasn't passed to the constructor and the component couldn't read the CSV file). This bug is now fixed as well. So, thank you for asking this question.
</blockquote></details>

Ok, good then. :+1:

**Review by jarkkoka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer)

**Review by jarkkoka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java, line 43 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/53#-MpGEC2jEYeYjEitPuCh:-MpGEC2jEYeYjEitPuCi:b-p68i78) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f0d8de64ff2e23691131ad61de02f20ba905ef51/src/main/java/fi/hsl/jore/importer/feature/batch/scheduled_stop_point/ScheduledStopPointExportProcessor.java#L43)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         Optional<String> elyNumber = jore3Stop.elyNumber();
>         if (elyNumber.isEmpty() || elyNumber.get().isEmpty()) {
>             LOGGER.debug("Jore 3 stop with id: {} isn't processed any further because it has no ely number",
>                     jore3Stop.externalId().value()
>             );
>             return null;
>         }
> 
>         final int nationalId = Integer.parseInt(elyNumber.get());
> ```
</details>


I'd prefer more idiomatic Java:

```
        final String elyNumber = jore3Stop.elyNumber().filter(str -> !str.isEmpty()).orElse(null);

        if (elyNumber == null) {
            LOGGER.debug("Jore 3 stop with id: {} isn't processed any further because it has no ely number",
                    jore3Stop.externalId().value()
            );
            return null;
        }

        final int nationalId = Integer.parseInt(elyNumber);
```

**Pull request merged**
