### PR TITLE
Import lines to Jore 4 database

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56)* status: all files reviewed, 8 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/common/JdbcRowMapperUtil.java, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjmAsR4G4hRaN4bjQk:-MpjmAsR4G4hRaN4bjQl:b-v9ju0t) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/main/java/fi/hsl/jore/importer/feature/batch/common/JdbcRowMapperUtil.java#L16)):*
> ```
> JdbcRowMapperUtil
> ```

I don't fully understand why this class is introduced when there already exists `JsonbConverter` class. Can you elaborate a little bit how is this different?
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportMapper.java, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjltMbACWaLIwl-vET:-MpjltMcCISAoXaDFIGp:bbb5cy1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportMapper.java#L27)):*
> ```
> rowMapperUtil.multilingualStringFromJsonString(resultSet.getString("name")
> ```

E.g. in `LineHeader` about the same is done with:

```
    converter.fromJson(record.getNetworkLineHeaderName(), MultilingualString.class)
```
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjrcspBuDRjiq1kZ_i:-MpjrcspBuDRjiq1kZ_j:bsqkat9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L32)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                     Map.of(
>                             JoreLocaleUtil.FINNISH.toString(),
>                             FINNISH_NAME,
>                             JoreLocaleUtil.SWEDISH.toString(),
>                             SWEDISH_NAME
>                     )
> ```
</details>


A handy utility method could be added to `JoreLocaleUtil` that would take Finnish and Swedish name as parameter to make this code more concise and non-repeatable.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjrtZkCFtI05ByClJb:-MpjrtZkCFtI05ByClJc:bg4r9bt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L41)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                     Map.of(
>                             JoreLocaleUtil.FINNISH.toString(),
>                             FINNISH_SHORT_NAME,
>                             JoreLocaleUtil.SWEDISH.toString(),
>                             SWEDISH_SHORT_NAME
>                     )
> ```
</details>


same comment as above
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjsZGK-NE2USWKpTLv:-MpjsZGK-NE2USWKpTLw:b599mm4) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L80)):*
> ```
>             final String finnishName = line.shortName()
>                     .values()
>                     .getOrElse(JoreLocaleUtil.FINNISH.toString(), "");
> ```

You could make this class more concise and easier to read by introducing a helper method:

```

private static String i18n(final Map<Locale, String> localisations, final Locale locale) {
    return localisations.values().getOrElse(locale.toString(), "");
}
```

The above method could be possibly(?) moved to `JoreLocaleUtil` and statically imported into this class and other places where it is used.

The method would be used like below:

```

final String finnishName = i18n(line.shortName(), JoreLocaleUtil.FINNISH);
```
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportReaderTest.java, line 78 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjuLWx5l0iorbqez1v:-MpjuLWx5l0iorbqez1w:b-o93jwy) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportReaderTest.java#L78)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             final String finnishName = line.name()
>                     .values()
>                     .get(JoreLocaleUtil.FINNISH.toString())
>                     .getOrNull();
> ```
</details>


See my comment on `i18n` method on another test. This is a little bit different but not much. It is a bit boring to read multiple repeating lines when things could be done in a more elegant and concise way.
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/entity/VehicleModeTest.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjumIe-uNS0uKA90L6:-MpjumIe-uNS0uKA90L7:b-brbah5) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/transmodel/entity/VehicleModeTest.java#L24)):*
> ```
>                 final VehicleMode vehicleMode = VehicleMode.of(NetworkType.METRO_TRACK);
>                 assertThat(vehicleMode).isEqualTo(VehicleMode.METRO);
> ```

I would have done these kind of tests in a for loop to reduce verbosity. Verbosity makes reviewing slow and errors in test logic hard to discern. Actually I did not bother to look too closely at all the different test methods with only the slightest difference between them. But tastes are different. No need to change since this is already written with good test coverage.
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/repository/TransmodelLineRepositoryTest.java, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-Mpjv_hW8TauR5QjeYmg:-Mpjv_hW8TauR5QjeYmh:b-36a567) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/transmodel/repository/TransmodelLineRepositoryTest.java#L64)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>                         Map.of(
>                                 JoreLocaleUtil.FINNISH.toString(),
>                                 FINNISH_NAME,
>                                 JoreLocaleUtil.SWEDISH.toString(),
>                                 SWEDISH_NAME
>                         )
> ```
</details>


Same comment than in another class. You could really reduce repeating code drastically by extracting repeating code into common methods. My favourite principle in coding is DRY = Don't Repeat Yourself.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56)* status: 14 of 26 files reviewed, 8 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportMapper.java, line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjltMbACWaLIwl-vET:-Mpou9dK6vGU4NNzKIfR:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/main/java/fi/hsl/jore/importer/feature/batch/line/LineExportMapper.java#L27)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> rowMapperUtil.multilingualStringFromJsonString(resultSet.getString("name")
> ```

E.g. in `LineHeader` about the same is done with:

```
    converter.fromJson(record.getNetworkLineHeaderName(), MultilingualString.class)
```
</blockquote></details>

This is now fixed.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjrcspBuDRjiq1kZ_i:-Mpp2wlwC-YTHAQQsqyE:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L32)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                     Map.of(
>                             JoreLocaleUtil.FINNISH.toString(),
>                             FINNISH_NAME,
>                             JoreLocaleUtil.SWEDISH.toString(),
>                             SWEDISH_NAME
>                     )
> ```

A handy utility method could be added to `JoreLocaleUtil` that would take Finnish and Swedish name as parameter to make this code more concise and non-repeatable.
</blockquote></details>

This is now fixed.
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjsZGK-NE2USWKpTLv:-Mpp3wmj93NhriwFJrVa:b-3idypd) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L80)):*
> private static String i18n(final Map<Locale, String> localisations, final Locale locale) {
>     return localisations.values().getOrElse(locale.toString(), "");
> }
This is now fixed (I added a new method to the `JoreLocaleUtil` class)
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportReaderTest.java, line 78 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjuLWx5l0iorbqez1v:-Mpp41gd07u22sRKQkJk:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportReaderTest.java#L78)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>             final String finnishName = line.name()
>                     .values()
>                     .get(JoreLocaleUtil.FINNISH.toString())
>                     .getOrNull();
> ```

See my comment on `i18n` method on another test. This is a little bit different but not much. It is a bit boring to read multiple repeating lines when things could be done in a more elegant and concise way.
</blockquote></details>

This is now fixed.
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/entity/VehicleModeTest.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjumIe-uNS0uKA90L6:-MppAS0c7DHtWAscd-Ke:bdcirt8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/transmodel/entity/VehicleModeTest.java#L24)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                 final VehicleMode vehicleMode = VehicleMode.of(NetworkType.METRO_TRACK);
>                 assertThat(vehicleMode).isEqualTo(VehicleMode.METRO);
> ```

I would have done these kind of tests in a for loop to reduce verbosity. Verbosity makes reviewing slow and errors in test logic hard to discern. Actually I did not bother to look too closely at all the different test methods with only the slightest difference between them. But tastes are different. No need to change since this is already written with good test coverage.
</blockquote></details>

Good point. I actually did fix this because replacing these tests with a parameterized test was quite easy.
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/repository/TransmodelLineRepositoryTest.java, line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-Mpjv_hW8TauR5QjeYmg:-Mpp4fOq65MONOcD2HOw:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/transmodel/repository/TransmodelLineRepositoryTest.java#L64)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                         Map.of(
>                                 JoreLocaleUtil.FINNISH.toString(),
>                                 FINNISH_NAME,
>                                 JoreLocaleUtil.SWEDISH.toString(),
>                                 SWEDISH_NAME
>                         )
> ```

Same comment than in another class. You could really reduce repeating code drastically by extracting repeating code into common methods. My favourite principle in coding is DRY = Don't Repeat Yourself.
</blockquote></details>

This is now fixed.
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/common/JdbcRowMapperUtil.java, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjmAsR4G4hRaN4bjQk:-MpotYio8lZg9uBS_pZr:b-55gwee) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/main/java/fi/hsl/jore/importer/feature/batch/common/JdbcRowMapperUtil.java#L16)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> JdbcRowMapperUtil
> ```

I don't fully understand why this class is introduced when there already exists `JsonbConverter` class. Can you elaborate a little bit how is this different?
</blockquote></details>

Good catch. The `JsonbConverter` required `org.jooq.JSONB` object, but when I am working with JDBC, I have a `String` object. That said, I removed this class and added a new method to the `IJsonbConverter` interface => I can use `JsonbConverter` here instead of introducing a different class which does the same thing.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56)* status: 14 of 26 files reviewed, 8 unresolved discussions (waiting on @jarkkoka and @jschummer)

___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjrtZkCFtI05ByClJb:-MppCNFmDnl1ZnmVgPEO:b-23ogcm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L41)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
>                     Map.of(
>                             JoreLocaleUtil.FINNISH.toString(),
>                             FINNISH_SHORT_NAME,
>                             JoreLocaleUtil.SWEDISH.toString(),
>                             SWEDISH_SHORT_NAME
>                     )
> ```

same comment as above
</blockquote></details>

This is also fixed.

**Review by jarkkoka — APPROVED** [review]
Good work!

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-:-Mppcde175mK4gBunM3E:b-onzvv2)* status: all files reviewed, 4 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/util/JoreLocaleUtil.java, line 19 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MppQRVX9ZocO3ww58F7:-MppQRVX9ZocO3ww58F8:byhauya) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/568a3e1bfd0476746195b75187ecaf846f98b00b/src/main/java/fi/hsl/jore/importer/feature/jore3/util/JoreLocaleUtil.java#L19)):*
> ```
> finnish
> ```

"Finnish" (with capital letter) in description text
___
*[src/main/java/fi/hsl/jore/importer/feature/jore3/util/JoreLocaleUtil.java, line 20 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MppQXg513lcS6A3L2z7:-MppQXg60llr1EmTp_ix:b-ebl5qm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/568a3e1bfd0476746195b75187ecaf846f98b00b/src/main/java/fi/hsl/jore/importer/feature/jore3/util/JoreLocaleUtil.java#L20)):*
> ```
> swedish
> ```

"Swedish" (with capital letter) in description text
___
*[src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java, line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjsZGK-NE2USWKpTLv:-MppQwpR6_oAqmbHUG2I:brchfpr) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/batch/line/LineExportProcessorTest.java#L80)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

> private static String i18n(final Map<Locale, String> localisations, final Locale locale) {
>     return localisations.values().getOrElse(locale.toString(), "");
> }
This is now fixed (I added a new method to the `JoreLocaleUtil` class)
</blockquote></details>

Ok, great! :+1: 
___
*[src/test/java/fi/hsl/jore/importer/feature/transmodel/entity/VehicleModeTest.java, line 24 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjumIe-uNS0uKA90L6:-Mppc-5L6D8tu-B8Hn9d:b-ns7n4e) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/test/java/fi/hsl/jore/importer/feature/transmodel/entity/VehicleModeTest.java#L24)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Good point. I actually did fix this because replacing these tests with a parameterized test was quite easy.
</blockquote></details>

Nice. :1st_place_medal: 
___
*[src/main/java/fi/hsl/jore/importer/feature/batch/common/JdbcRowMapperUtil.java, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/56#-MpjmAsR4G4hRaN4bjQk:-MppcYb2BgDMIcRXWeiM:bhdw0i1) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/c4c5a2c3994b3fd378738f6fea64e9ac8aae606c/src/main/java/fi/hsl/jore/importer/feature/batch/common/JdbcRowMapperUtil.java#L16)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

Good catch. The `JsonbConverter` required `org.jooq.JSONB` object, but when I am working with JDBC, I have a `String` object. That said, I removed this class and added a new method to the `IJsonbConverter` interface => I can use `JsonbConverter` here instead of introducing a different class which does the same thing.
</blockquote></details>

Sounds a reasonable solution.

**Pull request merged**
