### PR TITLE
Add version history to link and node tables

### PR DESCRIPTION
**Pull request by lassemaatta**
- Upserting entities will NOT alter history
  if the source entity matches the destination
  entity

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)

### CODE REVIEW

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_o_jx3HTvSHXOaiGR:-Mb_o_jx3HTvSHXOaiGS:bhete1m) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java#L18)):*
> ```Java
>     int countHistory();
> 
>     boolean emptyHistory();
> ```

Should this rather be called "isEmpty" or "isEmptyHistory"? (To me looks like "History" suffix in these functions isn't very useful)
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 154 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_q8WsDKhZ8_arYiqi:-Mb_q8Wt9hHxjCrUyJjM:b-s3pnss) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L154)):*
> ```Java
>     @Transactional(readOnly = true)
>     public int countHistory() {
>         //noinspection ConstantConditions
> ```

I don't understand this comment. Same comment is also in `NodeRepository.java`. Is it copypaste error or is this just some Java magic that I'm not aware of?
___
*[src/main/resources/db/migration/V1__init_temporal.sql, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_qclxEc7CR7MsPHn7:-Mb_qclxEc7CR7MsPHn8:b-940etz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V1__init_temporal.sql#L13)):*
> ```TSQL
>     manipulate              jsonb;
>     ignore_unchanged_values bool;
>     commonColumns           text[];
> ```

Are these names defined by us of do they come from somewhere else? Seems like all other variables are in snake_case, so camelCase here looks inconsistent.

(also i think that "timestamp" should rather be `timestamp` than `time_stamp`
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_vHIlCJm9HpqgTCRu:-Mb_vHIlCJm9HpqgTCRv:b-lrla1l) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L28)):*
> ```Java
>     private static final Point GEOM = GeometryUtil.toPoint(
>             GeometryUtil.SRID_WGS84,
>             new Coordinate(60.168988620, 24.949328727, 0)
> ```

This coordinate seems to be the same on all three points... Should it be defined only once and used everywhere? (Not a big issue though since the coordinate value doesn't seem to be used anywhere)

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @tk-vincit)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_o_jx3HTvSHXOaiGR:-Mb_yZcM6VDGJaRGTInZ:b-vyees6) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should this rather be called "isEmpty" or "isEmptyHistory"? (To me looks like "History" suffix in these functions isn't very useful)
</blockquote></details>

First, I often don't use the "javabeans conventions", ie `.getFirstName()` vs `.firstName()` or `.isEmpty()` vs `.empty()`. 

Second, I use the `History` suffix to avoid name conflicts with other interfaces (in this case `IBasicCrudRepository`, which already has a `count()` and `empty()` methods).
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 154 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_q8WsDKhZ8_arYiqi:-Mb_zgxp0bZTAW3KZ2A5:b-y00b0p) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L154)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand this comment. Same comment is also in `NodeRepository.java`. Is it copypaste error or is this just some Java magic that I'm not aware of?
</blockquote></details>

Ah, this comment is just a linter hint for Intellij IDEA, which otherwise would complain that because`selectCount()` returns an `Integer` it might theoretically be `null`.
___
*[src/main/resources/db/migration/V1__init_temporal.sql, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_qclxEc7CR7MsPHn7:-Mba-Nvs-7YHUuCJChOA:b-kjo2ml) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V1__init_temporal.sql#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Are these names defined by us of do they come from somewhere else? Seems like all other variables are in snake_case, so camelCase here looks inconsistent.

(also i think that "timestamp" should rather be `timestamp` than `time_stamp`
</blockquote></details>

See comment at the top of the file: This comes from the `temporal_tables` extension. I certainly don't know enough postgresql magick to write something like this by myself :)
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_vHIlCJm9HpqgTCRu:-Mba-tlT6b78VFLZuLs6:b-4en0zw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L28)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This coordinate seems to be the same on all three points... Should it be defined only once and used everywhere? (Not a big issue though since the coordinate value doesn't seem to be used anywhere) 
</blockquote></details>

It's three different coordinates: 60 & 24, 61 & 25, and 62 & 26.

These coordinates are used to alter the point location in the tests, so that we may observe that the old versions are moved into the history table.

**Review by tk-vincit — COMMENTED** [review]
Looks good to me, but I think that someone with more Java (+SQL) experience should also take a look.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-:-Mba2jnYBP25JqYmw4f_:b-nsjof4)* status: 0 of 20 files reviewed, all discussions resolved (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_o_jx3HTvSHXOaiGR:-Mba2AWE8VaElNbpxdWl:b-mtvfjk) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java#L18)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

First, I often don't use the "javabeans conventions", ie `.getFirstName()` vs `.firstName()` or `.isEmpty()` vs `.empty()`. 

Second, I use the `History` suffix to avoid name conflicts with other interfaces (in this case `IBasicCrudRepository`, which already has a `count()` and `empty()` methods).
</blockquote></details>

:shrug: ok. I'm not familiar with Java conventions, but guess this is fine then. :+1: 
___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java, line 154 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_q8WsDKhZ8_arYiqi:-Mba2MBk1HV726F8qjFF:bevsic7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/link/repository/LinkRepository.java#L154)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Ah, this comment is just a linter hint for Intellij IDEA, which otherwise would complain that because`selectCount()` returns an `Integer` it might theoretically be `null`.
</blockquote></details>

:heavy_check_mark: 
___
*[src/main/resources/db/migration/V1__init_temporal.sql, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_qclxEc7CR7MsPHn7:-Mba2S0ZENAhupA_8ZAW:b4putsz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V1__init_temporal.sql#L13)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

See comment at the top of the file: This comes from the `temporal_tables` extension. I certainly don't know enough postgresql magick to write something like this by myself :)
</blockquote></details>

:ok_hand: 
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 28 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_vHIlCJm9HpqgTCRu:-Mba2YVf7I50CaMwjpKw:b-stalgk) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L28)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

It's three different coordinates: 60 & 24, 61 & 25, and 62 & 26.

These coordinates are used to alter the point location in the tests, so that we may observe that the old versions are moved into the history table.

</blockquote></details>

Ah, missed the small difference. :joy:

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 19 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: 19 of 20 files reviewed, 7 unresolved discussions (waiting on @lassemaatta)

___
*[src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_o_jx3HTvSHXOaiGR:-MbaefM3EzapbOhEVxQ1:bdz6eou) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/java/fi/hsl/jore/importer/feature/infrastructure/common/repository/IHistoryRepository.java#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

:shrug: ok. I'm not familiar with Java conventions, but guess this is fine then. :+1: 
</blockquote></details>

Ok, here "emptyHistory" does not mean "clearHistory" (in imperative). But someone could mistakenly read it that way.
___
*[src/main/resources/db/migration/V1__init_temporal.sql, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_MKrj8cBO4uyUqsK7:-Mb_MKrj8cBO4uyUqsK8:bcbani7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V1__init_temporal.sql#L1)):*
> ```
> -- from https://github.com/nearform/temporal_tables/commit/6ba58c78d68d59b2d95cfc22223729309f0c4c72
> ```

Should original MIT license text be copied as preamble into this file?
___
*[src/main/resources/db/migration/V5__init_links.sql, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mbaax_s17Iu98oTFcuj:-Mbaax_s17Iu98oTFcuk:bnwcfsc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V5__init_links.sql#L2)):*
> ```
> -- TODO: We should probably not store Jore 3 stuff directly in the "infrastructure" schema
> --       Instead, we should have a "jore3" schema, which hosts all the raw data from Jore 3
> ```

I agree with a separate "jore3" schema.
___
*[src/main/resources/db/migration/V5__init_links.sql, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbabF91DuL1zTiwmMyO:-MbabF91DuL1zTiwmMyP:bez676q) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V5__init_links.sql#L12)):*
> ```
> including intermediate points
> ```

Should this be read as "includes only intermediate points"?
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbaiVi81EQqn0U0kpJw:-MbaiVi81EQqn0U0kpJx:b-azqdh8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L53)):*
> ```
> final Instant after = Instant.now()
> ```

There is an assumption that `after` is always greater than `before`. Theoretically, these variables can have same value but in practice they probably always differ. If there is a slightest chance that this test could fail nondeterministically I would at least add a comment about it here. Or maybe add something like this:

  assumeTrue("`after` is expected to be greater than `before`", after > before)
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 144 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mbal4xyDP_HF0dZEXPq:-Mbal4xyDP_HF0dZEXPr:b-p6l0zm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L144)):*
> ```
> oldestEntity.systemTime().range()
> ```

 With regard to style I would declare a variable for repeating chained expression to improve readability (YMMV).

Good test coverage anyway which is more essential!
___
*[src/main/resources/db/migration/V4__init_nodes.sql, line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbaYo9i7wDKVGTvSf4O:-MbaYo9i7wDKVGTvSf4P:b-66mofk) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V4__init_nodes.sql#L42)):*
> ```
>     EXCLUDE USING GIST (infrastructure_node_id WITH =, infrastructure_node_sys_period WITH &&)
> ```

Well-crafted constraint. Awkward syntax but does its job well.
___
*[src/main/resources/db/migration/V4__init_nodes.sql, line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbaaNl357EF_k7a8StS:-MbaaNl357EF_k7a8StT:btmbdyh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V4__init_nodes.sql#L50)):*
> ```
> true, true
> ```

Based on documentation, the fourth (last) parameter means "Ignore updates without actual change". However, did not find the meaning of the third parameter which is here set to true. A comment would explain it to the reader.

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: 19 of 20 files reviewed, 7 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/resources/db/migration/V1__init_temporal.sql, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mb_MKrj8cBO4uyUqsK7:-Mbapc044P03CsnhyJwC:b-ovwaw7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V1__init_temporal.sql#L1)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> -- from https://github.com/nearform/temporal_tables/commit/6ba58c78d68d59b2d95cfc22223729309f0c4c72
> ```

Should original MIT license text be copied as preamble into this file?
</blockquote></details>

Good idea.
___
*[src/main/resources/db/migration/V5__init_links.sql, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbabF91DuL1zTiwmMyO:-Mbaomrs7bfwO6BdXbwX:b-lho0z0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V5__init_links.sql#L12)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> including intermediate points
> ```

Should this be read as "includes only intermediate points"?
</blockquote></details>

Nope, it also includes the link endpoints (ie. the two node positions) as well as the intermediate points (jr_piste). Otherwise there would be small gaps between links if we graph them in eg. QGis
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 53 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbaiVi81EQqn0U0kpJw:-Mbap9Mv8zPVXcMoKoPL:b-fjmyoi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L53)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> final Instant after = Instant.now()
> ```

There is an assumption that `after` is always greater than `before`. Theoretically, these variables can have same value but in practice they probably always differ. If there is a slightest chance that this test could fail nondeterministically I would at least add a comment about it here. Or maybe add something like this:

  assumeTrue("`after` is expected to be greater than `before`", after > before)
</blockquote></details>

`upsert` goes to the database and back so I'd assume the likelyhood of a collision is rather low.
___
*[src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java, line 144 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-Mbal4xyDP_HF0dZEXPq:-MbapR1D70DR7Mn1YEjE:bgjp24t) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/test/java/fi/hsl/jore/importer/feature/common/dto/mixin/SystemTimeTest.java#L144)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> oldestEntity.systemTime().range()
> ```

 With regard to style I would declare a variable for repeating chained expression to improve readability (YMMV).

Good test coverage anyway which is more essential!
</blockquote></details>

True, I'll refactor this.
___
*[src/main/resources/db/migration/V4__init_nodes.sql, line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbaaNl357EF_k7a8StS:-MbaoeNv2wwhvHcyBJbz:b3wqa9t) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V4__init_nodes.sql#L50)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> true, true
> ```

Based on documentation, the fourth (last) parameter means "Ignore updates without actual change". However, did not find the meaning of the third parameter which is here set to true. A comment would explain it to the reader.
</blockquote></details>

Good point. I actually found the definition in the original `temporal_tables` extension (the binary version, which is not Azure compatible): https://github.com/arkhipov/temporal_tables#update-conflicts-and-time-adjustment

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: 18 of 20 files reviewed, 7 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/resources/db/migration/V4__init_nodes.sql, line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbaaNl357EF_k7a8StS:-MbeuZ6T6ZjiQA8gglBv:be9u1ec) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V4__init_nodes.sql#L50)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Good point. I actually found the definition in the original `temporal_tables` extension (the binary version, which is not Azure compatible): https://github.com/arkhipov/temporal_tables#update-conflicts-and-time-adjustment
</blockquote></details>

I added a description of the boolean parameters into the migration, where the extension is introduced.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: all files reviewed, 5 unresolved discussions (waiting on @jarkkoka and @lassemaatta)

___
*[src/main/resources/db/migration/V1__init_temporal.sql, line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbjTC_R4OiyytNPqkXI:-MbjTC_S4imOyQ5f1Ygo:b-htxznj) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7f504ae6da1264e7d7e2462e2c25187df602d061/src/main/resources/db/migration/V1__init_temporal.sql#L14)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> -- where the two boolean parameters are:
> -- 1: If true, try to mitigate against concurrent updates against the same rows
> --    (https://github.com/arkhipov/temporal_tables#update-conflicts-and-time-adjustment)
> -- 2: If true, ignore updates without actual changes
> --    (https://github.com/nearform/temporal_tables#ignore-updates-without-actual-change)
> ```
</details>


:+1: 
___
*[src/main/resources/db/migration/V5__init_links.sql, line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7#-MbabF91DuL1zTiwmMyO:-MbjSj2zC8EdUgRUrZS4:b3r1nnn) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/ee9b99d1a24fd12739eec5c4fd5eeb0f3359bc68/src/main/resources/db/migration/V5__init_links.sql#L12)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Nope, it also includes the link endpoints (ie. the two node positions) as well as the intermediate points (jr_piste). Otherwise there would be small gaps between links if we graph them in eg. QGis
</blockquote></details>

Ok, thanks for clarification.

**Review by jarkkoka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/7)* status: all files reviewed, 3 unresolved discussions (waiting on @lassemaatta)

**Pull request merged**
