### PR TITLE
Add missing steps to the Setup section

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[README.md, line 194 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71#-Mv3FmpF7C5C85QhCjm0:-Mv3FmpF7C5C85QhCjm1:b-lxdrcc) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/5ea7ae1854b68aafea1fda571701b255b414bac6/README.md#L194)):*
> ```Markdown
>     ```
> 3. Adjust the `source.db.*` properties in `profiles/dev/config.<my-username>.properties` to your needs. Other configuration for destination database and test database may also be found from here.
> 4. If you wish to connect to the original JORE3 database, follow the instructions [here](https://github.com/HSLdevcom/jore4/blob/main/wiki/onboarding.md#creating-an-ssh-configuration-entry) on how to create a tunnel and connect to the database. After the tunnel is created, the jore3 database will be available on localhost:56239. Ask for the username and password from the project team. 
> ```

There are inconsistent references to Jore3 in this document e.g.  `Jore3`,`Jore 3` (space in between), `JORE3` (caps). It would more elegant to stick to one exact form and use it everywhere.



_Code quote:_
```Markdown
JORE3
```
___
*[README.md, line 197 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71#-Mv3GJaI5LqkYz9uOOl6:-Mv3GJaI5LqkYz9uOOl7:b2a41k7) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/5ea7ae1854b68aafea1fda571701b255b414bac6/README.md#L197)):*
> ```Markdown
> 5. Clone the [jore4-digiroad-import](https://github.com/HSLdevcom/jore4-digiroad-import) repository and 
>    follow these steps:
>    1. Run the digiroad import.
> ```

Digiroad (uppercase initial)



_Code quote:_
```Markdown
digiroad
```

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[README.md, line 194 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71#-Mv3FmpF7C5C85QhCjm0:-MvO036x22yDyQvfW47S:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/5ea7ae1854b68aafea1fda571701b255b414bac6/README.md#L194)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

There are inconsistent references to Jore3 in this document e.g.  `Jore3`,`Jore 3` (space in between), `JORE3` (caps). It would more elegant to stick to one exact form and use it everywhere.
</blockquote></details>

This is now fixed.
___
*[README.md, line 197 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71#-Mv3GJaI5LqkYz9uOOl6:-MvO051K6pjlo3my7C90:be1y2gh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/5ea7ae1854b68aafea1fda571701b255b414bac6/README.md#L197)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Digiroad (uppercase initial)
</blockquote></details>

This is now fixed

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer and @pallost)

**Comment by pkainulainen-vincit** [comment]
This was rebased manually.

**Pull request closed without merging**
