### PR TITLE
Split db migrations into smaller chunks

### PR DESCRIPTION
**Pull request by lassemaatta**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5)

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
Note that there isn't (or at least there shouldn't be) any concrete changes here; I just split the migrations so that it's easier to see what tables/indexis are modified in later commits.

These will all be later replaced once the migrations are handled by the hasura db image.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5#-:-MagdB1GETKGFJuJIDAp:bbrr1iw)* status: 0 of 5 files reviewed, all discussions resolved

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5)* status: all files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[src/main/resources/db/migration/V4__init_links.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5#-Mai-K8T9Hv8bo2bhnn0:-Mai-K8T9Hv8bo2bhnn1:bazkvjh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e4a4d4175fbfb1f570baa659b00605bcb4c201c2/src/main/resources/db/migration/V4__init_links.sql#L10)):*
> ```
> Geometry
> ```

geometry != geography

**Review by lassemaatta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5)* status: all files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[src/main/resources/db/migration/V4__init_links.sql, line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5#-Mai-K8T9Hv8bo2bhnn0:-Mb-t0jZ4oECESsDeSf0:b8a0nnl) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/e4a4d4175fbfb1f570baa659b00605bcb4c201c2/src/main/resources/db/migration/V4__init_links.sql#L10)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> Geometry
> ```

geometry != geography
</blockquote></details>

Yeah, I know that PostGIS differentiates between `geography` and `geometry` types, but my intent was not to reference the actual physical column types (as they're just an implementation detail) but rather just describe to the reader the semantics of this column. Perhaps a better way would be to say "A line from start -> end"?

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lassemaatta)

**Pull request merged**
