### PR TITLE
Improve the description of the transmodelExportFlow flow

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 198 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jzkzm6e6NBuMpLtLF:-N2jzkzm6e6NBuMpLtLG:buo61y3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L198)):*
> ```Markdown
> 
> * The `prepareTransmodelExportStep` step deletes the data found from the target tables.
> * The `exportScheduledStopPointsStep` step imports scheduled stop points from the importer's database to the Jore 4 database.
> ```

IMO here could be reference to the section below explaining the logic of processing stop points having same short-ID.



_Code quote:_
```Markdown
exportScheduledStopPointsStep
```
___
*[`README.md` line 199 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jywO5CDV6_djrNtz8:-N2jywO5CDV6_djrNtz9:b-6ciddg) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L199)):*
> ```Markdown
> * The `prepareTransmodelExportStep` step deletes the data found from the target tables.
> * The `exportScheduledStopPointsStep` step imports scheduled stop points from the importer's database to the Jore 4 database.
> * The `exportLinesStep` step imports lines from the importer's database to the Jore 4 database.
> ```

Not all lines from Jore3 are imported because of overlapping activity periods. IMO this should be documented here or (within the `importLinesFlow`if filtering is done there).



_Code quote:_
```Markdown
exportLinesStep
```
___
*[`README.md` line 201 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jzHy422wVReNNgcmD:-N2jzHy422wVReNNgcmE:b-seljlz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L201)):*
> ```Markdown
> * The `exportLinesStep` step imports lines from the importer's database to the Jore 4 database.
> * The `exportRoutesStep` step imports route metadata from the importer's database to the Jore 4 database. This step
>   imports a route metadata to the Jore 4 database only if the line which owns the processed route metadata was imported 
> ```

If I recall it right, there is also another "if" condition: a route is NO transferred to Jore4 if it has overlapping activity periods with other routes. IMO this should be documented here as well (or in the corresponding import step if filtering is done there).



_Code quote:_
```Markdown
only if
```
___
*[`README.md` line 239 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jyTXhEXYpqfIwQWUB:-N2jyTXiCg7dgT3ZHAPg:bzduyq3) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L239)):*
> ```Markdown
> 
> * The imported stop points are sorted in ascending the order by using the external id (Jore 3 id). If multiple scheduled
>   stop points have the same short id, the first one is transferred to Jore 4. This ensures that multiple stop points
> ```

I think this is obsolete, isn't it? You made changes to the logic how scheduled stop point is picked from the ones having same short-ID.

Probably you should review this whole "scheduled stop points" section?



_Code quote:_
```Markdown
the first one is transferred to Jore 4
```

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 199 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jywO5CDV6_djrNtz8:-N2kLWdV3CwJuTHTyHhn:bsg8my8) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L199)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Not all lines from Jore3 are imported because of overlapping activity periods. IMO this should be documented here or (within the `importLinesFlow`if filtering is done there).
</blockquote></details>

I documented this to the "non-obvious assumptions" section.
___
*[`README.md` line 201 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jzHy422wVReNNgcmD:-N2kLdF-BtfzX3lqosI8:btm33ru) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L201)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

If I recall it right, there is also another "if" condition: a route is NO transferred to Jore4 if it has overlapping activity periods with other routes. IMO this should be documented here as well (or in the corresponding import step if filtering is done there).
</blockquote></details>

I documented this to the "non-obvious assumptions" section.
___
*[`README.md` line 239 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jyTXhEXYpqfIwQWUB:-N2kLen3C7ebmVz2QDIv:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L239)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I think this is obsolete, isn't it? You made changes to the logic how scheduled stop point is picked from the ones having same short-ID.

Probably you should review this whole "scheduled stop points" section?
</blockquote></details>

This is now fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`README.md` line 198 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2jzkzm6e6NBuMpLtLF:-N2kNDkH32iP0y6_OEs9:b-77j5lv) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/4545ceafefa7a35b8c4e78e42a9e3884c65bd2f2/README.md#L198)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO here could be reference to the section below explaining the logic of processing stop points having same short-ID.
</blockquote></details>

I added links to end of a step description if the step in question has non-obvious assumptions.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Good additions in rev3-4!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-:-N2kRs-Q09QWMg83UKxo:b-h15k22)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 243 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kPFWF2Ww0p9AaJs19:-N2kPFWF2Ww0p9AaJs1A:bnuph4n) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L243)):*
> ```Markdown
> * If the ely number of a scheduled stop point isn't found from the database of the importer, it won't be transferred
>   to Jore 4.
> * The import process ignores Digiroad stop points which have invalid information (such as empty or missing ely number).
> ```

"scheduled" (since in Digiroad data there exists ELY number for all public transport stops).



_Code quote:_
```Markdown
Digiroad
```
___
*[`README.md` line 253 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kPllN474oTDFN7u1C:-N2kPllN474oTDFN7u1D:b-ldrhbx) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L253)):*
> ```Markdown
>     of the found Digiroad stop point is combined with the data read from the importer's database. The combined stop point
>     data is imported to the Jore 4 database.
>   * If the import process has iterated all ely numbers and none of them was found from the Digiroad data, the importer
> ```

not critical observation but minor detail: all "ely" instances should be in uppercase since it is an abbreviation (ELY = "Elinkeino-, liikenne- ja ympäristö"-keskus)

You may change this e.g. in a separate commit later.



_Code quote:_
```Markdown
ely
```
___
*[`README.md` line 260 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kRCLK6YkmPqrad2cH:-N2kRCLK6YkmPqrad2cI:blwgdwa) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L260)):*
> ```Markdown
> ##### Lines
> 
> * If multiple lines with the same label and priority have overlapping validity periods, only one line is inserted into
> ```

Could explain the logic for selecting one line of the available candidates (having overlapping validity period). Or is it mentioned elsewhere?



_Code quote:_
```Markdown
only one line
```
___
*[`README.md` line 266 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kSJZw5KPpBPvbqpKv:-N2kSJZw5KPpBPvbqpKw:b-10ggok) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L266)):*
> ```Markdown
> 
> * When the importer queries the start and end stop points of an exported route from the importer's database, it 
>   will "group" stop points by using short id and selects the stop point that was exported to Jore 4 database. 
> ```

"and for each group selects the one that was exported previously"



_Code quote:_
```Markdown
and selects the stop point that was exported
```
___
*[`README.md` line 267 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kReiQ1romdS8RmNV6:-N2kReiQ1romdS8RmNV7:b-khoagz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L267)):*
> ```Markdown
> * When the importer queries the start and end stop points of an exported route from the importer's database, it 
>   will "group" stop points by using short id and selects the stop point that was exported to Jore 4 database. 
> * If multiple routes with same label and priority have overlapping validity periods, only one route is inserted into the
> ```

Could explain the logic for selecting one route of the available candidates (having overlapping validity period). Or is it mentioned elsewhere?



_Code quote:_
```Markdown
only one route is inserted
```
___
*[`README.md` line 277 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kS9kH2YJp87mHD4o9:-N2kS9kH2YJp87mHD4oA:b-10ggok) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L277)):*
> ```Markdown
> 
> * When the importer queries the stop points of a journey pattern from the importer's database, it 
>   will "group" stop points by using short id and selects the stop points which were exported to Jore 4 database.
> ```

"and for each group selects the one that was exported previously"



_Code quote:_
```Markdown
and selects the stop points which were exported
```

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 243 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kPFWF2Ww0p9AaJs19:-N2ki-ve4fqcGqjDUfnh:b-q3rekz) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L243)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"scheduled" (since in Digiroad data there exists ELY number for all public transport stops).
</blockquote></details>

This sentence is no longer prosent in the latest version of this PR. I am not sure how it's still visible here.
___
*[`README.md` line 253 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kPllN474oTDFN7u1C:-N2kiIk87tQ1qMYVZh__:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L253)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

not critical observation but minor detail: all "ely" instances should be in uppercase since it is an abbreviation (ELY = "Elinkeino-, liikenne- ja ympäristö"-keskus)

You may change this e.g. in a separate commit later.
</blockquote></details>

This is now fixed.
___
*[`README.md` line 260 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kRCLK6YkmPqrad2cH:-N2kj3qs8mAe0m9MQ0Xb:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L260)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Could explain the logic for selecting one line of the available candidates (having overlapping validity period). Or is it mentioned elsewhere?
</blockquote></details>

This is now fixed.
___
*[`README.md` line 266 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kSJZw5KPpBPvbqpKv:-N2kjBPy8pYEuhm9jz3T:b-kyqw8z) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L266)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"and for each group selects the one that was exported previously"
</blockquote></details>

this is now fixed.
___
*[`README.md` line 277 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kS9kH2YJp87mHD4o9:-N2kj5XU2OII52VRDVov:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L277)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"and for each group selects the one that was exported previously"
</blockquote></details>

This is now fixed.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 266 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kSJZw5KPpBPvbqpKv:-N2ksEat2uy5x1-H2KoQ:be04fqh) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L266)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Or is it? At least for me in r5 does not appear like so.
</blockquote></details>

It seems that I forgot to commit before push. anyway, this should be fixed now (again).

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[`README.md` line 267 at r3](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kReiQ1romdS8RmNV6:-N2oPpwL9YUkB69X8Itj:bd37imt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/93d95afc2506ad5b7230993d89308269b1448996/README.md#L267)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Could explain the logic for selecting one route of the available candidates (having overlapping validity period). Or is it mentioned elsewhere?
</blockquote></details>

This is explained in the following sentence.
___
*[`README.md` line 264 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kkcJxEPXnwQ0W5nJ1:-N2oPjUf3MpzDk6HMUex:bcc2cve) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f51e72c5a513d21d55657f6ffe6280d99024d43e/README.md#L264)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"is the first line found from the query results (with no specific ordering)"

assuming the result set is not ordered
</blockquote></details>

I added a sentence that describes the sorting logic.
___
*[`README.md` line 274 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2kkSzl3K5FlNFOfC_-:-N2oQ7FN1W2sIPrsHlq6:bcvnh00) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f51e72c5a513d21d55657f6ffe6280d99024d43e/README.md#L274)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

"is the first route found from the query results (with no specific ordering)"

assuming the result set is not ordered
</blockquote></details>

I added a sentence which explains the sorting logic.
___
*[`README.md` line 284 at r5](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2klV5s1kw09wIbDSsm:-N2oQGHaE04UpZXlyPQf:bnc8khb) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/f51e72c5a513d21d55657f6ffe6280d99024d43e/README.md#L284)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

double "and"
</blockquote></details>

Removed the second and.

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: all files reviewed, 4 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 227 at r8](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2pFLPy6B7jydheuZlp:-N2pMRiD4cS5qOOsL0FS:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/b7b8df8e41a6ca8eea152951ee8205e56b3194f9/README.md#L227)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would add the following sentence at the end of this paragraph (bulletin point):

"Currently, not all database constraints of Jore4 database are implemented or taken into account in internal data processing logic of Importer. Hence, writing a data item into Jore4 database may fail because of a database constraint violation. As a consequence of constraint violations, subsequent steps of Spring Batch run may see a reduced number of data items remaining to be processed."
</blockquote></details>

Fixed.
___
*[`README.md` line 246 at r8](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2pBELoE98SbP-C1EGG:-N2pMi-JB5_PuB0R7FDm:b-qlmipi) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/b7b8df8e41a6ca8eea152951ee8205e56b3194f9/README.md#L246)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I still see the "Digiroad" word here. During earlier review round I requested to change the quoted text to "scheduled stop points" because in Digiroad public transport stop data there are no empty or missing ELY numbers.
</blockquote></details>

The importer must process possible errors which occur when it reads the CSV file which contains the Digiroad stop points and the most logical way to handle these errors is to ignore the Digiroad stop point in question and write a line to the log file. For example, at the moment some Digiroad stop points are ignored because they have unknown direction. However, I did remove the example from this bullet point so that people don't think that this is a common scenario.
___
*[`README.md` line 254 at r8](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2pBpXl1MIcLJAb-X5c:-N2pMeRq5p24WuxFdupT:bt2vr1b) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/b7b8df8e41a6ca8eea152951ee8205e56b3194f9/README.md#L254)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I would add the following sentence at the end of this paragraph (bulletin point):

"For each stop point the collected data items from Digiroad are: (1) the Digiroad ID of the infrastructure link along which the stop point is located and (2) the direction of traffic with regard to direction of the linestring geometry of the associated infrastructure link (reversed or not). All the other data items originate from Jore3."
</blockquote></details>

Fixed.

**Review by jarkkoka — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jarkkoka, @jschummer, @pallost, and @pkainulainen-vincit)

___
*[`README.md` line 246 at r8](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85#-N2pBELoE98SbP-C1EGG:-N2pWpSq2x5GI6R6l1St:b-445ynw) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/b7b8df8e41a6ca8eea152951ee8205e56b3194f9/README.md#L246)):*
<details><summary><i>Previously, pkainulainen-vincit (Petri Kainulainen) wrote…</i></summary><blockquote>

The importer must process possible errors which occur when it reads the CSV file which contains the Digiroad stop points and the most logical way to handle these errors is to ignore the Digiroad stop point in question and write a line to the log file. For example, at the moment some Digiroad stop points are ignored because they have unknown direction. However, I did remove the example from this bullet point so that people don't think that this is a common scenario.
</blockquote></details>

Sounds reasonable. Please include your suggestion.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer and @pallost)

**Pull request merged**
