### PR TITLE
Write test script which tests the infrastructure node import process

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
This test script ensures that:

* The data which is read from the jr_solmu database table is processed correctly.
* The processed data is written to the infrastructure_network.infrastructure_nodes database table.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27)

### CODE REVIEW

**Review by tk-vincit — COMMENTED** [review]
Looks good to me. You can judge if someone else should also take a look at this.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27#-:-MjDaqeb3N4RTh4JKDM2:b-lonr3v)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jarkkoka and @jschummer)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pkainulainen-vincit)

___
*[testing/README.md, line 6 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27#-MjDamO44S5LpXKzQLtk:-MjDamO44S5LpXKzQLtl:b-xlhz9g) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/254fc244a4561187c3f83eeb32070e689168e7fb/testing/README.md#L6)):*
> ```Markdown
> import job is working as expected. The testing process has three steps:
> 
> 1. Export the source data from the Microsoft SQL server database to a CSV file.
> ```

Could you also mention a bit more clear that which source and which destination databases are you using? Do you intend to use the original JORE3 DEV database? If yes, could you point to e.g. this wiki page: https://github.com/HSLdevcom/jore4/blob/main/wiki/onboarding.md#creating-an-ssh-configuration-entry to help the developer setting up the connection there?

And I assume, you are using the dockerized postgresql image as a destination, so should mention that that is started up with `./development.sh start:deps`
___
*[testing/README.md, line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27#-MjDcSjo553-hWJZt3md:-MjDcSjp1vhM9J0CDYiY:bd7frmt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/254fc244a4561187c3f83eeb32070e689168e7fb/testing/README.md#L30)):*
> ```Markdown
> * The processed data is written to the `infrastructure_network.infrastructure_nodes` database table.
> 
> You can run this test script by following these steps:
> ```

I'd restructure this part of the README a bit:
1. clarify that the python script's task is to 1. load an input CSV, 2. run the import transformation and 3. compare the results to the expected output CSV
2. then tell about the steps that how the developer could produce the desired input and output CSV data sets, using the `sqlcmd` and `psql` commands (as you did below)

.. should mention somewhere that the `sqlcmd` export is expected to be taken from the jore3 database through the bastion host tunnel
.. should mention somewhere that to be able to take an export with the `psql` command, the developer should in fact already run the whole importing process once that the dockerized database is populated with data
___
*[testing/README.md, line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27#-MjDbhHa42MzMjJV0IBm:-MjDbhHb2kfyn2O2mn-9:bukjwjm) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/254fc244a4561187c3f83eeb32070e689168e7fb/testing/README.md#L36)):*
> ```Markdown
> 
> ```
> sqlcmd -S localhost,56239 -d joretest -U joretest_reader -Q "SELECT n.soltunnus AS soltunnus,n.soltyyppi AS soltyyppi,
> ```

could mention in a few words what data this query is retrieving from the jore3 database. E.g. "This query retrieves all valid Node objects (jr_solmu) from the JORE3 database"

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/27)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jarkkoka and @jschummer)

**Comment by pkainulainen-vincit** [comment]
I rebased the commits manually in order to avoid merge commit.

**Pull request closed without merging**
