### PR TITLE
Run dependencies by using Docker compose bundle

### PR DESCRIPTION
**Pull request by pkainulainen-vincit**
- Remove local MSSQL docker configuration.
- Ensure that Docker runs all required dependencies.
- Update the MSSQL db configuration found from profile specific
  properties files.
- Update .gitignore
- Update development.sh

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49)

### CODE REVIEW

**Review by jarkkoka — COMMENTED** [review]
> Reviewed 9 of 12 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer, @pallost, and @pkainulainen-vincit)

___
*[development.sh, line 53 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-Mnyz-8VEzMyv_-tHn6H:-Mnyz-8VEzMyv_-tHn6I:bpl5tv0) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/development.sh#L53)):*
> ```
> imported
> ```

I think it should be emphasised that "imported and transformed" because otherwise this database can be confused with jore4-mssltestdb.
___
*[development.sh, line 54 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-MnyzOXcAIn3Hst8fPVb:-MnyzOXcAIn3Hst8fPVc:bvu3iky) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/development.sh#L54)):*
> ```
> imported
> ```

something like "imported and transformed"

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49)* status: all files reviewed, 4 unresolved discussions (waiting on @jschummer and @pkainulainen-vincit)

___
*[development.sh, line 93 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-Mnz3dA4CMKHTTqazzoK:-Mnz3dA4CMKHTTqazzoL:bhrbn8k) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/development.sh#L93)):*
> ```Shell
> 
> if [[ ${COMMAND} == "stop" ]]; then
>   docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.custom.yml down
> ```

you could create a shortcut variable for this:
`DOCKER_COMPOSE_CMD="docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.custom.yml"`

and then use it like this:
`$DOCKER_COMPOSE_CMD down`

(and ofc also in the other functions below)
___
*[docker/docker-compose.custom.yml, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-Mnz4RSd135t0HR2d3fZ:-Mnz4RSd135t0HR2d3f_:bcuje81) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/docker/docker-compose.custom.yml#L4)):*
> ```YAML
> version: "3.8"
> services:
>   importer:
> ```

these customizations are all fine for now to ease the transition to the docker-compose bundle. Later on of course it would be better to keep these as minimal as possible because all entries to this file mean a deviation to the e2e setup

**Review by pkainulainen-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @jarkkoka, @jschummer, and @pallost)

___
*[development.sh, line 53 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-Mnyz-8VEzMyv_-tHn6H:-MnzDtcX32DGQn8Lr21v:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/development.sh#L53)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> imported
> ```

I think it should be emphasised that "imported and transformed" because otherwise this database can be confused with jore4-mssltestdb.
</blockquote></details>

This is now fixed.
___
*[development.sh, line 54 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-MnyzOXcAIn3Hst8fPVb:-MnzDvCiBeTJgr2BmMcP:b-8iw4jt) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/development.sh#L54)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

> ```
> imported
> ```

something like "imported and transformed"
</blockquote></details>

This is fixed as well.
___
*[development.sh, line 93 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-Mnz3dA4CMKHTTqazzoK:-MnzDwTM0YV3IhdBq0sT:b9hnsd9) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/development.sh#L93)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could create a shortcut variable for this:
`DOCKER_COMPOSE_CMD="docker-compose -f ./docker/docker-compose.yml -f ./docker/docker-compose.custom.yml"`

and then use it like this:
`$DOCKER_COMPOSE_CMD down`

(and ofc also in the other functions below)
</blockquote></details>

This is now fixed.
___
*[docker/docker-compose.custom.yml, line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49#-Mnz4RSd135t0HR2d3fZ:-MnzDyLdAzSb8cApe4ro:bkhp78f) ([raw file](https://github.com/hsldevcom/jore4-jore3-importer/blob/7290a5b8087993ad76b9c8eae9f071b88e07f874/docker/docker-compose.custom.yml#L4)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

these customizations are all fine for now to ease the transition to the docker-compose bundle. Later on of course it would be better to keep these as minimal as possible because all entries to this file mean a deviation to the e2e setup
</blockquote></details>

I agree :)

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @jschummer)

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-jore3-importer/49)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @jarkkoka and @jschummer)

**Pull request merged**
